# -*- coding: utf-8 -*-
"""
John & Them — album data (Uncle Theology's first album).

Hip-hop / urban-gospel meditations on the Johannine writings and their
neighbors. Lyrics transcribed verbatim from the booklet (John & Them.pdf);
each song keeps its section labels ([Verse 1], [Chorus], …) as stanza labels.
Scripture is the booklet's per-song "Inspired by" list.

Teaching aids (thesis/facts/moves/terms/questions) are NOT yet populated for
this album — they render only when present, so the pages show player + lyrics
+ scripture until the study layer is added.
"""

ALBUM = {
    "title": "John & Them",
    "slug": "john-and-them",
    "order": 1,
    "tagline": "Uncle Theology · Lyrics & Scripture",
    "blurb": (
        "Street-gospel hip-hop through the eyes of John and his neighbors — "
        "abiding in the fire, Chesterton's fence, the bread of Judas, and the "
        "long road home — over boom-bap and gospel-choir beats."
    ),
    "cover": "/assets/john-and-them/cover.png",
    "audio_prefix": "john-and-them",
    # Urban graffiti identity — cool navy night, neon cyan + magenta.
    "theme": {
        "--bg": "#0a0d14",
        "--bg-2": "#10141e",
        "--surface": "#151b28",
        "--surface-2": "#1d2535",
        "--rule": "#2b3447",
        "--ink": "#eef2f9",
        "--ink-soft": "#c3cbdb",
        "--ink-faint": "#7e89a1",
        "--green": "#d65ad6",
        "--green-deep": "#9b3fb0",
        "--gold": "#36d6ec",
        "--gold-deep": "#1f9fb8",
        "--link": "#36d6ec",
        "--glow-a": "rgba(54,214,236,0.12)",
        "--glow-b": "rgba(214,90,214,0.08)",
    },
    "episode": {
        "order": 6,
        "title": "John & Them — the whole album, sung and explained",
        "guid": "utr-john-and-them-2026-07-22",
        "pubDate": "Mon, 20 Jul 2026 12:00:00 -0500",
        "duration": "51:43",
        "length": 74718528,
        "audio_url": "https://sermons-cdn.sermonsteward.com/uncle-theology/podcast/john-and-them.mp3",
        "image": "https://sermons-cdn.sermonsteward.com/uncle-theology/podcast/john-and-them-art.jpg",
        "summary": (
            "John & Them played end to end — street-gospel hip-hop through the eyes of the apostle "
            "John and his neighbors — with a short spoken intro before every song. Abiding in light "
            "and love, the finished gospel, Chesterton's fence and chronological snobbery, the "
            "assurance of the new birth, the rich young ruler, Jude against the false teachers, the "
            "antichrist spirit of 'Christ plus,' the bread handed to Judas, the prodigal's one road "
            "home, and the Creator born of the creature."
        ),
        "chapters": [
            ("0:00", "Intro — Abide in the Fire"),
            ("0:52", "Abide in the Fire"),
            ("5:43", "Intro — Keep It Simple Stupid"),
            ("6:25", "Keep It Simple Stupid"),
            ("8:56", "Intro — Chesterton's Fence"),
            ("9:39", "Chesterton's Fence"),
            ("13:08", "Intro — Double John"),
            ("13:48", "Double John"),
            ("18:26", "Intro — RYR (Rich Young Ruler)"),
            ("19:08", "RYR (Rich Young Ruler)"),
            ("24:02", "Intro — Titus, Tim, & Them"),
            ("24:40", "Titus, Tim, & Them"),
            ("27:13", "A word from our sponsor — Providence Community Church"),
            ("27:31", "Intro — Jude"),
            ("28:15", "Jude"),
            ("32:20", "Intro — AntiChrist"),
            ("33:04", "AntiChrist"),
            ("36:14", "Intro — Bread of Judas"),
            ("36:54", "Bread of Judas"),
            ("40:49", "Intro — One Road Home (The Prodigal)"),
            ("41:36", "One Road Home (The Prodigal)"),
            ("45:17", "Intro — Noel"),
            ("46:03", "Noel"),
        ],
    },
}

SONGS = [
    {
        "num": 1,
        "title": "Abide in the Fire",
        "slug": "abide-in-the-fire",
        "about": (
            "John said God is Light and God is Love — and the call is to abide in "
            "both, staying with the Word that was from the beginning rather than "
            "running from the flame."
        ),
        "thesis": (
            "John says God is Light and God is Love — and the believer’s whole "
            "life is to abide in both, staying with the Word that was from the "
            "beginning rather than running from the fire that exposes and "
            "purifies."
        ),
        "facts": [
            ("Doctrine", "Assurance · Abiding · Christology"),
            ("Anchor text", "1 John · John 15, 17"),
            ("Form", "Boom-bap · spoken-word"),
            ("Voices", "The Apostle John"),
        ],
        "moves": [
            {"label": "God is Light and Love", "text": "The two great claims of 1 John; the believer stands “in between ’em,” walking the line in the blood (1 John 1:5; 4:8)."},
            {"label": "New biology, not religion", "text": "Not climbing a ladder to heaven — heaven came to the street. “Christ in my veins”: it’s ontology, not apology (1 John 3:1–2; 4:9)."},
            {"label": "The polished antichrist", "text": "Not horns but a “Jesus plus” — a Judas in Jordans who loves the world, not the Word; the anointing is the counter-encryption (1 John 2:18–20, 27)."},
            {"label": "Abide in the fire", "text": "The farewell-discourse flame (John 15, 17) re-lit in the epistle: keep His commands, remain in His love, and the same fire that burns lies keeps you (John 15:9–10; 17:24–26)."},
        ],
        "terms": [
            {"term": "abide / remain (menō)", "gloss": "John’s signature word — to stay and dwell in Christ (John 15:4; 1 John 2:24)."},
            {"term": "God is Light / God is Love", "gloss": "The two defining statements of 1 John (1:5; 4:8)."},
            {"term": "“Jesus plus”", "gloss": "The antichrist spirit — adding anything to Christ as if He weren’t enough (1 John 2:18–23)."},
            {"term": "the anointing", "gloss": "The Spirit’s teaching that lets believers discern truth and abide (1 John 2:20, 27)."},
            {"term": "ontology, not apology", "gloss": "The hook: identity (“I am” in Christ) grounds action, rather than action trying to earn identity."},
        ],
        "discussion": [
            "John insists God is both Light and Love. Where do churches tend to emphasize one at the expense of the other — and what goes wrong when they do?",
            "The song’s antichrist “ain’t wearin’ horns” — he’s polite, in the pulpit, selling “Jesus plus.” What does a “Jesus plus” gospel look like in our own setting?",
            "“Abide in the fire, don’t run from the flame.” What makes a community want to run, and what does staying look like for us together?",
        ],
        "contemplation": [
            "Where are you tempted to “run from the flame” — to dodge the light that exposes you?",
            "Is your faith more “apology” (trying to become someone) or “ontology” (acting from who you already are in Christ)?",
            "What would it mean today to “stay with the Word that was from the beginning” in one concrete area of your life?",
        ],
        "kind": "verse",
        "blocks": [
            {"label": "Intro — Spoken", "lines": [
                "Yo, John said, God is Light.",
                "Then he doubled down, God is Love.",
                "And I’m standin’ in between ’em,",
                "Tryna walk this line in the blood.",
            ]},
            {"label": "Verse 1 — The Test of Life", "lines": [
                "I ain’t talkin’ religion, I’m talkin’ rebirth,",
                "From the dirt to divine, man, I’m God’s workmanship, word.",
                "They told me do good, but that ladder don’t reach,",
                "You don’t climb to heaven, son — heaven came to the street.",
                "Fake saints build towers, Babel-brand believers,",
                "Self-help preachers, dopamine achievers.",
                "Law without love? That’s a tomb with a mirror.",
                "Grace without awe? That’s a god gettin’ nearer — to you.",
                "It’s ontology, not apology.",
                "I act ’cause I am, not ’cause I’m tryna be.",
                "It’s inside-out, that’s divine physiology,",
                "Christ in my veins, that’s new biology.",
                "Behold what manner of love, yeah, I’m gawkin’ in awe,",
                "The infinite’s intimate — my dirt became law.",
            ]},
            {"label": "Chorus — Abide in the Fire", "lines": [
                "Abide in the fire, don’t run from the flame,",
                "The same God who saves is the One who remains.",
                "Light burns lies, but it keeps me sane,",
                "So I stay, I stay — in the holy name.",
            ]},
            {"label": "Verse 2 — Antichrist Ethos", "lines": [
                "Yo, I seen the antichrist — he ain’t wearin’ horns,",
                "He’s in the pulpit, polite, with a platinum form.",
                "He smiles when he sells you a Jesus plus,",
                "Add ambition, add wealth, subtract trust.",
                "He’s an insider, not an outsider,",
                "A Judas in Jordans, a soul divider.",
                "He loves the world, not the Word,",
                "Builds brands, not brotherhood — fame preferred.",
                "But I got the anointing, Holy Ghost encryption,",
                "No counterfeit can crack this conviction.",
                "Truth tattooed deep, Son and Father are one.",
                "Who denies that bond? Yo, the war’s begun.",
                "So I’m stayin’ with the Word that was from the beginning,",
                "That’s my weapon and my witness — truth keeps me winning.",
            ]},
            {"label": "Chorus — Abide in the Fire", "lines": [
                "Abide in the fire, don’t run from the flame,",
                "The same God who saves is the One who remains.",
                "Light burns lies, but it keeps me sane,",
                "So I stay, I stay — in the holy name.",
            ]},
            {"label": "Bridge — Spoken, Slow, Low, Prophetic Tone", "lines": [
                "Whoever confesses the Son has the Father.",
                "That’s ontology.",
                "That’s identity.",
                "That’s eternity in real time.",
                "So when they ask who I am,",
                "I just say — He is.",
            ]},
            {"label": "Beat Drop — Double-Time", "lines": [
                "I heard Him pray in the night, Glorify Me, right?",
                "That’s the spark in John seventeen’s light.",
                "Then He passed that flame, said Abide in My name,",
                "And the torch hit John’s pen when he’d write.",
                "Same tone, same zone, same throne flow,",
                "You in Me and I in You, that’s home, bro.",
                "From the Upper Room to the exile’s tomb,",
                "He kept that boom of the Bridegroom’s echo.",
                "Farewell words turned fuel for the saints.",
                "He said Love each other, John inked it with paint.",
                "Spirit’s comin’, Counselor’s hummin’,",
                "That’s the current that keeps us from runnin’.",
                "Now the letter hits hard like a second-hand summon,",
                "You know, you know, no bluffin’, no frontin’.",
                "Light from the Last Supper drippin’ through the parchment.",
                "Truth tasted blood, now the ink’s still fragrant.",
                "If you keep My commands, you’ll remain in My love,",
                "John fifteen lives again in the dove.",
                "The world’s gonna hate you, but I overcame,",
                "And First John’s claim is the same refrain.",
                "Anointing abides, that’s chapter two.",
                "Spirit test spirits, that’s four’s review.",
                "As He is, so are we, that’s ontology turnin’ biography.",
                "From vine to branch, that’s divine psychology.",
            ]},
            {"label": None, "lines": [
                "Farewell discourse became battle discourse,",
                "When the aged apostle re-lit the Source.",
                "God is Light.",
                "God is Love.",
                "And the course stays true,",
                "From the Upper Room promise",
                "To the letter to you.",
            ]},
            {"label": "Final Chorus / Outro", "lines": [
                "Abide in the fire, don’t run from the flame,",
                "The same God who saves is the One who remains.",
                "Light burns lies, but it keeps me sane,",
                "So I stay, I stay — in the holy name.",
            ]},
        ],
        "refs": [
            "1 John 1:5–7",
            "1 John 2:24–27",
            "1 John 4:7–17",
            "John 15:4–10",
            "John 17:20–23",
        ],
    },
    {
        "num": 2,
        "title": "Keep It Simple Stupid",
        "slug": "keep-it-simple-stupid",
        "about": (
            "A mantra against over-complicating the gospel: it is finished, you "
            "can’t improve it — whoever believes that Christ is God is born of "
            "God, and that faith overcomes the world."
        ),
        "thesis": (
            "The gospel is finished — you can’t improve it. Whoever believes that "
            "Christ is God is born of God, and that new birth, not your striving, "
            "is what overcomes the world."
        ),
        "facts": [
            ("Doctrine", "Assurance · Faith · Simplicity of the gospel"),
            ("Anchor text", "1 John 5:1–5"),
            ("Form", "Soul-sample boom-bap"),
            ("Voices", "—"),
        ],
        "moves": [
            {"label": "Stop complicating it", "text": "The instinct to over-think the simplest things; the words that keep us straight are simply to act on God’s real heart (1 John 5:3)."},
            {"label": "Born again, then love", "text": "Whoever believes Christ is God is made new — and those who love God love the brothers too (1 John 5:1)."},
            {"label": "It is finished", "text": "KISS: the gospel’s done, you can’t improve it; the doubting fades as you get used to grace (John 19:30; 1 Corinthians 15:1–4)."},
            {"label": "Victory already won", "text": "His commands aren’t burdensome, the world can’t compete, and the snakes are crushed beneath our feet (1 John 5:4; Genesis 3:15)."},
        ],
        "terms": [
            {"term": "KISS", "gloss": "“Keep It Simple, Stupid” — a design maxim attributed to U.S. Navy engineer Kelly Johnson (1960): the best solution is the least complicated one. The song borrows it for the finished gospel."},
            {"term": "“It is finished”", "gloss": "Jesus’ cry from the cross — Greek tetelestai, a word stamped on paid bills meaning “paid in full” (John 19:30). The basis for “you can’t improve it.”"},
            {"term": "“snakes crushed beneath our feet”", "gloss": "The protoevangelium of Genesis 3:15 — the seed crushing the serpent’s head — echoed in Romans 16:20."},
            {"term": "“overcomes the world”", "gloss": "1 John 5:4–5: it is faith, not effort, that is the victory."},
        ],
        "discussion": [
            "Why do we instinctively complicate the gospel? Where have you seen “Christianity-plus” creep into a church?",
            "The song ties love for God and love for the brothers together as a package. How should that shape how a group treats its hardest members?",
            "“His commands are not burdensome.” Is that your experience? Why or why not?",
        ],
        "contemplation": [
            "Where are you “stalling out before you start” by overcomplicating obedience?",
            "“It is finished.” What are you still trying to add to a finished work?",
            "What would resting in “keep it simple” change about this week?",
        ],
        "kind": "verse",
        "blocks": [
            {"label": "Intro — Spoken Word | Sparse Soul Sample", "lines": [
                "I complicate the simplest things,",
                "And stall out before I start.",
                "So here’s the words that keep me straight —",
                "To act on God’s real heart.",
            ]},
            {"label": "Verse 1 — Laid-Back Rap | Pocket Flow", "lines": [
                "Whoe’er believes that Christ is God",
                "In Him he is made new.",
                "And those who love the Lord above",
                "Will love the brothers too.",
            ]},
            {"label": "Chorus — Mantra Hook", "lines": [
                "KISS stands for keep it simple, stupid.",
                "The gospel’s done — you can’t improve it.",
                "You’ll keep doubting till you get used to it.",
                "It is finished — keep it simple, stupid.",
            ]},
            {"label": "Verse 2 — Teaching Verse", "lines": [
                "This is how we know we love God’s",
                "Children as we should.",
                "When love for God is manifest,",
                "His commands to us feel good.",
            ]},
            {"label": "Chorus — Mantra Hook", "lines": [
                "KISS stands for keep it simple, stupid.",
                "The gospel’s done — you can’t improve it.",
                "You’ll keep doubting till you get used to it.",
                "It is finished — keep it simple, stupid.",
            ]},
            {"label": "Verse 3 — Confident Delivery", "lines": [
                "His orders are not burdensome,",
                "The world cannot compete.",
                "Real victory that our faith has won,",
                "Snakes crushed beneath our feet.",
            ]},
            {"label": "Chorus — Half-Time Feel", "lines": [
                "KISS stands for keep it simple, stupid.",
                "The gospel’s done — you can’t improve it.",
                "You’ll keep doubting till you get used to it.",
                "It is finished — keep it simple, stupid.",
            ]},
            {"label": "Outro — Repetition / Fade", "lines": [
                "Keep it simple, stupid…",
                "Keep it simple…",
                "It is finished…",
                "Keep it simple…",
            ]},
        ],
        "refs": [
            "1 John 5:1–5",
            "Matthew 11:28–30",
            "John 19:30",
            "1 Corinthians 15:1–4",
        ],
    },
    {
        "num": 3,
        "title": "Chesterton’s Fence",
        "slug": "chestertons-fence",
        "about": (
            "Don’t tear down what you don’t understand. The gospel is a fence "
            "built from the beginning — no new Christs, no upgrades; the original "
            "is winning."
        ),
        "thesis": (
            "Don’t tear down what you don’t understand. The gospel is a fence "
            "built from the beginning — and the “chronological snobbery” that "
            "mocks the old just for being old will bleed you out; the original "
            "Christ is still winning."
        ),
        "facts": [
            ("Doctrine", "Tradition · Sufficiency of the gospel"),
            ("Anchor text", "Jude 3 · 1 John 2:24"),
            ("Form", "Gospel choir call-and-response"),
            ("Voices", "G.K. Chesterton · C.S. Lewis"),
        ],
        "moves": [
            {"label": "The fence parable", "text": "Chesterton: don’t remove a fence till you know why it was built. The cross looks weak till grace explodes in resurrection light (Jude 3)."},
            {"label": "Don’t cut the wire", "text": "You ask why it’s there before you decide; the gospel’s fence is amazing grace, not a flaw to fix or a system to mend (1 John 2:24)."},
            {"label": "Chronological snobbery", "text": "“Clive” warns that truth doesn’t age — mocking the past as obsolete is itself a fashion that will rot (Hebrews 13:8)."},
            {"label": "No new Christs", "text": "Same Christ reigning from start to end; it needs no edits from modern man (Proverbs 22:28)."},
        ],
        "terms": [
            {"term": "Chesterton’s fence", "gloss": "From G.K. Chesterton’s The Thing (1929): before you tear down a fence whose purpose you can’t see, first find out why it was put there. A rule against reckless “reform.”"},
            {"term": "“Clive”", "gloss": "C.S. Lewis — Clive Staples Lewis — pictured “in the corner, pipe smoke in the air.”"},
            {"term": "chronological snobbery", "gloss": "A phrase Lewis credits to Owen Barfield (in Surprised by Joy): the uncritical assumption that whatever is newer is truer, and the old is discredited simply for being old."},
            {"term": "“ancient landmark”", "gloss": "Proverbs 22:28, “do not move the ancient landmark your fathers have set,” underlies the whole don’t-move-the-fence theme."},
            {"term": "“No new Christs, the original is winning”", "gloss": "The hook — a refrain this song shares with “AntiChrist” later on the album."},
        ],
        "discussion": [
            "Where in church life do people “tear down the fence” without first asking why it was built?",
            "Lewis’s “chronological snobbery” — where does our culture assume new = true? Where does the church?",
            "How do you tell a fence worth keeping from one worth removing?",
        ],
        "contemplation": [
            "What conviction or practice have you been tempted to discard mainly because it feels old or restrictive?",
            "Have you ever “bled out later asking, who knew?” — removed a guardrail and regretted it?",
            "Where do you need to trust that “you don’t improve perfection”?",
        ],
        "kind": "verse",
        "blocks": [
            {"label": "Intro — Gospel Choir Call and Response", "lines": [
                "Leader: What was true then?",
                "Crowd: True now!",
                "Leader: What saved us?",
                "Crowd: Christ alone!",
                "Leader: From the beginning—",
                "Crowd: We received it!",
                "Leader: No upgrades!",
                "Crowd: No replacements!",
                "Leader (spoken, half-beat pause): Say it like you mean it—",
                "All (together): The gospel doesn’t need improving!",
            ]},
            {"label": "Chorus", "lines": [
                "Don’t grow bored",
                "With what you had from beginning.",
                "No new Christs, the original is winning.",
                "To add something new is deadly sinning.",
            ]},
            {"label": "Verse 1 — Chesterton’s Fence", "lines": [
                "Chesterton said, Slow down, friend—look close,",
                "That fence you hate might save your bones.",
                "You tear it down ’cause you don’t see the use,",
                "Then bleed out later askin’, Who knew?",
                "Wisdom builds with a reason in mind,",
                "Not everything’s obvious at first glance.",
                "The cross looks weak, the law feels tight,",
                "Till grace explodes in resurrection light.",
                "You don’t cut the wire ’cause it shocks your pride,",
                "You ask why it’s there before you decide.",
                "So don’t dismantle what God put in place,",
                "The gospel’s fence is amazing grace.",
                "Not a flaw to fix or a system to mend,",
                "You don’t improve perfection — amen.",
            ]},
            {"label": "Chorus", "lines": [
                "Don’t grow bored",
                "With what you had from beginning.",
                "No new Christs, the original is winning.",
                "To add something new is deadly sinning.",
            ]},
            {"label": "Verse 2 — Clive / Chronological Snobbery", "lines": [
                "Clive in the corner, pipe smoke in the air,",
                "Said, Check your calendar — truth don’t age there.",
                "Just ’cause it’s old don’t mean it’s obsolete,",
                "That’s chronological snobbery trippin’ your feet.",
                "We mock the past like we’re smarter by birth,",
                "As if modern means the truest of truth.",
                "But fashions fade and opinions rot,",
                "While ancient light still exposes the dark.",
                "You think new thoughts make the old ones dumb,",
                "But the gospel worked before you come.",
                "Not upgraded by time or tweaked by trend,",
                "Same Christ reigning from start to end.",
                "If it was true when the blood first ran,",
                "It don’t need edits from modern man.",
            ]},
            {"label": "Chorus", "lines": [
                "Don’t grow bored",
                "With what you had from beginning.",
                "No new Christs, the original is winning.",
                "To add something new is deadly sinning.",
            ]},
            {"label": "Outro — Chant", "lines": [
                "From the beginning — we abide.",
                "Same old truth — still alive.",
                "No new Christs — no disguise.",
                "What He gave us — that suffices.",
                "(repeat, building)",
                "NO NEW CHRISTS!",
                "SAME OLD TRUTH!",
                "CHRIST IS ENOUGH!",
                "FOR ME AND YOU!",
            ]},
        ],
        "refs": [
            "1 John 2:24",
            "Jude 3",
            "Jeremiah 6:16",
            "Hebrews 13:8",
            "Proverbs 22:28",
        ],
    },
    {
        "num": 4,
        "title": "Double John",
        "slug": "double-john",
        "about": (
            "The Gospel of John and the first epistle of John in one breath — "
            "whoever trusts in Him is born again, secure in perpetuity: I’m His, "
            "and He cannot deny Himself."
        ),
        "thesis": (
            "Read the Gospel of John and his first epistle in one breath: whoever "
            "trusts in Christ has been born again and belongs to Him in "
            "perpetuity — “I’m His, and He cannot deny Himself.”"
        ),
        "facts": [
            ("Doctrine", "Assurance · New birth · Union with Christ"),
            ("Anchor text", "John 15, 17 · 1 John"),
            ("Form", "Trap-gospel"),
            ("Voices", "The Apostle John"),
        ],
        "moves": [
            {"label": "Born again = new ontology", "text": "Whoever trusts has been born again; “divine biology,” life hooked to eternity, security in perpetuity (1 John 5:1; John 3:3)."},
            {"label": "Same voice, two books", "text": "John 17’s high-priestly prayer and the farewell discourse re-lit in the epistle: “love one another” proves who’s in (John 13:34–35; 17)."},
            {"label": "The test of life", "text": "Walking in light, keeping His word, no fear in love — fruit, not lip-service optics (1 John 1:5–7; 4:18)."},
            {"label": "Kept to the end", "text": "“I’m His, and He cannot deny Himself”; abiding now builds confidence at His appearing (2 Timothy 2:13; 1 John 2:28)."},
        ],
        "terms": [
            {"term": "ontology / divine biology", "gloss": "The song’s repeated claim that the new birth is a change in being, not behavior — you act because you are."},
            {"term": "the farewell discourse", "gloss": "Jesus’ upper-room teaching, John 13–17, the source of “abide in My love” and the Counselor’s coming."},
            {"term": "“I’m His, and He cannot deny Himself”", "gloss": "Assurance grounded in God’s faithfulness rather than ours — 2 Timothy 2:13, “if we are faithless, He remains faithful.”"},
            {"term": "“no fear in love”", "gloss": "1 John 4:18 — “perfect love casts out fear.”"},
            {"term": "the dove", "gloss": "The Spirit/Counselor John 15 promises, who “keeps us from runnin’.”"},
        ],
        "discussion": [
            "John gives “tests of life” (light, love, belief). How can a community use them for assurance without turning them into anxiety?",
            "“Love one another — proves who is in and who ain’t.” How does that challenge the way we measure spiritual maturity?",
            "What’s the difference between assurance rooted in “He cannot deny Himself” and assurance rooted in our own performance?",
        ],
        "contemplation": [
            "Do you relate to God as someone trying to become His, or someone who already is His?",
            "Where does “no fear in love” need to replace fear in your walk?",
            "What would change if you truly believed your security is “in perpetuity”?",
        ],
        "kind": "verse",
        "blocks": [
            {"label": "Intro", "lines": [
                "Whoever trusts in Him",
                "has been born again.",
                "That’s ontology.",
                "Divine biology.",
                "Life hooked to eternity.",
                "Security in perpetuity.",
                "So when they ask who I think I am,",
                "I just say — yeah,",
                "I’m His!",
            ]},
            {"label": "Verse 1", "lines": [
                "I heard Him pray in the night, Glorify Me, right?",
                "That’s the spark in John seventeen’s light.",
                "So when He said, Abide in My name,",
                "And the Spirit hit John’s pen when he’d write.",
                "Same tone, same zone, same throne flow —",
                "Gospel of John, John one mo’.",
                "You in Me and I in You, that’s home, bro.",
            ]},
            {"label": "Chorus", "lines": [
                "I’m His",
                "(and He cannot deny Himself)",
                "I’m His",
                "(go get your Bible off the shelf)",
                "I’m His",
                "(open to anything writ by John)",
                "I’m His",
                "(and see the way we can belong)",
                "I’m His",
            ]},
            {"label": "Verse 2", "lines": [
                "From the Upper Room to the empty tomb, bro,",
                "Kept the sonic boom of the Bridegroom, bro.",
                "Farewell words turned fuel for the saints,",
                "Love one another — proves who is in and who ain’t.",
                "Spirit’s comin’ — Counselor’s hummin’,",
                "A current of power that keeps us runnin’.",
                "Now the letter hits hard like a second court summon,",
                "You know, you know, no bluffin’, no frontin’.",
                "Light from the Last Supper drippin’ through the parchment,",
                "Truth inked in blood — the plan is permanent.",
                "If you keep My commands, you’ll remain in My love,",
                "John fifteen comeback via the dove.",
                "The world’s gonna hate you, but I’ve overcome,",
                "First John’s claim is the same refrain.",
                "Anointing abides, that’s chapter two.",
                "Spirit test spirits, that’s another review.",
                "As He is, so are we — that’s ontology,",
                "Spiritual biology.",
                "From the vine to branch — divine physiology.",
                "Farewell discourse sets the Christian’s life course,",
                "When the aged apostle re-lit the Source.",
                "God is Light, God is Love,",
                "So the course stays true —",
                "Call back straight from the Upper Room,",
                "Another letter wrote to you.",
            ]},
            {"label": "Chorus", "lines": [
                "I’m His",
                "(and He cannot deny Himself)",
                "I’m His",
                "(go get your Bible off the shelf)",
                "I’m His",
                "(open to anything writ by John)",
                "I’m His",
                "(and see the way we can belong)",
                "I’m His",
            ]},
            {"label": "Verse 3", "lines": [
                "If we say we walk in light but dodge the glare, nah,",
                "John says that talk don’t breathe real air, nah.",
                "Upper Room logic, same diagnostic,",
                "Life shows fruit, not just lip-service optics.",
                "He who loves Me keeps My word, that’s stated.",
                "Epistle says if you don’t — you’re self-sedated.",
                "Not shamed, just named — clarity given,",
                "Born of God got God-family rhythms.",
                "Cain walked dark, Abel bled bright,",
                "Same old war replayed every night.",
                "But the test ain’t hype, gifts, or might,",
                "It’s love in flesh, lived in sight.",
                "No fear in love — that’s John four echoes,",
                "Farewell breath still in the letter’s chest, though.",
                "Perfect love casts terror out,",
                "Same voice, same truth, different route.",
            ]},
            {"label": "Chorus", "lines": [
                "I’m His",
                "(and He cannot deny Himself)",
                "I’m His",
                "(go get your Bible off the shelf)",
                "I’m His",
                "(open to anything writ by John)",
                "I’m His",
                "(and see the way we can belong)",
                "I’m His",
            ]},
            {"label": "Verse 4", "lines": [
                "They went out — but they weren’t of us.",
                "Same seed Jesus planted among us.",
                "Many will fall, many will lie,",
                "John heard it once — now he underlines.",
                "Antichrist spirit ain’t horns and smoke,",
                "It’s Christ-plus-self, diluted hope.",
                "Heard it from Christ: They’ll twist My name,",
                "Now the letter says, Don’t play that game.",
                "If it denies the Son — it loses the Father,",
                "No workaround, no doctrinal barter.",
                "But you? You got the oil still,",
                "Anointing teaching you — quiet, real.",
                "So don’t drift, don’t dim, don’t roam.",
                "Remain in Him till faith goes home.",
                "When He appears — no shrink, no flinch,",
                "Abiding now builds confidence then.",
            ]},
            {"label": "Final Chorus", "lines": [
                "I’m His",
                "(and He cannot deny Himself)",
                "I’m His",
                "(go get your Bible off the shelf)",
                "I’m His",
                "(open to anything writ by John)",
                "I’m His",
                "(and see the way we can belong)",
                "I’m His",
            ]},
        ],
        "refs": [
            "John 15:1–11",
            "John 17:1–23",
            "1 John 1:1–7",
            "1 John 2:3–6",
            "1 John 4:7–17",
        ],
    },
    {
        "num": 5,
        "title": "RYR (Rich Young Ruler)",
        "slug": "rich-young-ruler",
        "about": (
            "The rich young ruler walks away sorrowful — and a life built on "
            "balance sheets discovers the camel can only pass through the needle "
            "when grace breaks through."
        ),
        "thesis": (
            "The rich young ruler kept every rule and still walked away sorrowful "
            "— and a life built on balance sheets learns too late that the camel "
            "only passes through the needle when grace breaks through."
        ),
        "facts": [
            ("Doctrine", "Idolatry · Grace · Wealth"),
            ("Anchor text", "Matthew 19:16–26"),
            ("Form", "Cinematic trap"),
            ("Voices", "—"),
        ],
        "moves": [
            {"label": "The ledger faith", "text": "Prayers learned from balance sheets; counting barns before the grain; he checked the cost of following and walked away the same (Matthew 19:22; Luke 12:18)."},
            {"label": "Sunday-clothes religion", "text": "Quoting verses about the narrow road while paving highways for his own feet; gaining the world and feeling his soul slip out the door (Mark 8:36)."},
            {"label": "The serpent’s contract", "text": "“No apple, just a contract; no fire, just a pen” — he sold a crown he never had to be a king among men (Genesis 3)."},
            {"label": "Grace does the impossible", "text": "The needle wasn’t the problem, his clenched hand was; with God the camel passes right through (Matthew 19:26)."},
        ],
        "terms": [
            {"term": "the eye of a needle", "gloss": "Jesus’ image (Matthew 19:24) for how hard it is for the rich to enter the kingdom; the song takes it literally and personally."},
            {"term": "moth and rust", "gloss": "Matthew 6:19–20 — treasures stored on earth, where moth and rust destroy."},
            {"term": "“Ponzi scheme / the American dream”", "gloss": "The hook’s sting: a returns-chasing life that turns out to be the con — with the investor himself as the cost."},
            {"term": "“the wedding feast / oil I never bought”", "gloss": "An allusion to the ten virgins (Matthew 25:1–13): standing outside the feast with no oil."},
            {"term": "“I shook the serpent’s hand”", "gloss": "Eden re-staged as a business deal (Genesis 3) rather than a piece of fruit — the temptation as a contract."},
        ],
        "discussion": [
            "The ruler kept all the commands and still lacked one thing. What “one thing” tends to keep successful, moral people out of the kingdom?",
            "The song reframes the American dream as maybe “a Ponzi scheme.” Where do we bless greed as wisdom?",
            "“With man this is impossible, but with God…” How does that keep the song from becoming mere moralizing about money?",
        ],
        "contemplation": [
            "What would Jesus name as your “one thing” — the possession you couldn’t walk away from?",
            "Where are you “counting barns before the grain”?",
            "Is your hand clenched around a kingdom you were “never meant to stand”?",
        ],
        "kind": "verse",
        "blocks": [
            {"label": "Scripture — Matthew 19", "lines": [
                "And behold, a man came up to him, saying, Teacher, what good deed must I do to have eternal life?",
                "And he said to him, Why do you ask me about what is good? There is only one who is good. If you would enter life, keep the commandments.",
                "He said to him, Which ones?",
                "And Jesus said, You shall not murder, You shall not commit adultery, You shall not steal, You shall not bear false witness, Honour your father and mother, and, You shall love your neighbour as yourself.",
                "The young man said to him, All these I have kept. What do I still lack?",
                "Jesus said to him, If you would be perfect, go, sell what you possess and give to the poor, and you will have treasure in heaven; and come, follow me. When the young man heard this he went away sorrowful, for he had great possessions.",
                "And Jesus said to his disciples, Truly, I say to you, only with difficulty will a rich person enter the kingdom of heaven. Again I tell you, it is easier for a camel to go through the eye of a needle than for a rich person to enter the kingdom of God.",
                "When the disciples heard this, they were greatly astonished, saying, Who then can be saved?",
                "But Jesus looked at them and said, With man this is impossible, but with God all things are possible.",
            ]},
            {"label": "Verse 1", "lines": [
                "I learned my prayers from balance sheets,",
                "From men who smiled and shook my hand,",
                "They said the meek don’t own the earth",
                "If they don’t take it while they can.",
                "I tithed my hours, weighed my worth,",
                "Counted barns before the grain,",
                "He said, Follow Me, I checked the cost—",
                "Then I walked away the same.",
            ]},
            {"label": "Chorus", "lines": [
                "So here I am, the king of the land,",
                "Where moth and rust destroy,",
                "Oh the schemes that I’ve employed,",
                "But is it I who have been toyed with?",
                "Is it I who have been played?",
                "Was the reward long delayed—",
                "Just a Ponzi scheme…",
                "Or the American dream?",
            ]},
            {"label": "Verse 2", "lines": [
                "I wore my faith like Sunday clothes,",
                "Pressed and proper, clean and neat,",
                "Quoted verses ’bout the narrow road",
                "While paving highways for my feet.",
                "I heard the camel and the needle speak,",
                "Laughed it off as metaphor,",
                "But every mile I gained the world",
                "I felt my soul slip out the door.",
            ]},
            {"label": "Chorus", "lines": [
                "So here I am, the king of the land,",
                "Where moth and rust destroy,",
                "Oh the schemes that I’ve employed,",
                "But is it I who have been toyed with?",
                "Is it I who have been played?",
                "Was the reward long delayed—",
                "Just a Ponzi scheme…",
                "Or the American dream?",
            ]},
            {"label": "Verse 3", "lines": [
                "They said, You’re blessed, I said, Amen,",
                "When the numbers all went up,",
                "I called the rising tide my god",
                "And drank salvation from the cup.",
                "But prophets don’t read market trends,",
                "And crosses don’t compound,",
                "And every throne I climbed upon",
                "Was built on sinking ground.",
            ]},
            {"label": "Chorus", "lines": [
                "So here I am, the king of the land,",
                "Where moth and rust destroy,",
                "Oh the schemes that I’ve employed,",
                "But is it I who have been toyed with?",
                "Is it I who have been played?",
                "Was the reward long delayed—",
                "Just a Ponzi scheme…",
                "Or the American dream?",
            ]},
            {"label": "Bridge", "lines": [
                "I shook the serpent’s hand,",
                "He didn’t bare his teeth,",
                "He spoke of growth and timing,",
                "Said, You’re wiser than the meek.",
                "No apple, just a contract,",
                "No fire, just a pen,",
                "I sold the crown I never had",
                "To be a king among men.",
            ]},
            {"label": "Verse 4", "lines": [
                "Now I stand outside the wedding feast",
                "With oil I never bought,",
                "I traded mercy for a return",
                "And freedom for a thought.",
                "The Kingdom came without a price",
                "But I wouldn’t take it free,",
                "I bet my life on interest gains—",
                "Turns out the cost was me.",
            ]},
            {"label": "Final Bridge", "lines": [
                "I thought the needle was the problem,",
                "Turns out it was my hand.",
                "Still clenched around a kingdom",
                "I was never meant to stand.",
                "Then mercy did the impossible,",
                "What wealth could never do—",
                "The camel passed right through the eye",
                "When grace came breaking through.",
            ]},
            {"label": "Chorus", "lines": [
                "So here I am, the king of the land,",
                "Where moth and rust destroy,",
                "Oh the schemes that I’ve employed,",
                "But is it I who have been toyed with?",
                "Is it I who have been played?",
                "Was the reward long delayed—",
                "Just a Ponzi scheme…",
                "Or the American dream?",
            ]},
        ],
        "refs": [
            "Matthew 19:16–26",
            "Mark 10:17–27",
            "Luke 18:18–27",
            "Matthew 6:19–24",
        ],
    },
    {
        "num": 6,
        "title": "Titus, Tim, & Them",
        "slug": "titus-tim-and-them",
        "about": (
            "A Jude-tune on a First John album: calling out false teachers who "
            "turn godliness into profit — Jude, Titus, and Timothy showing them "
            "all dead wrong."
        ),
        "thesis": (
            "A Jude track on a John album: false teachers slip in, turning grace "
            "into a license and godliness into profit — but Jude, Titus, and "
            "Timothy hand the church the tools to call them out and hold the line."
        ),
        "facts": [
            ("Doctrine", "Discernment · False teaching"),
            ("Anchor text", "Jude 3–4 · Titus 1 · 1–2 Timothy"),
            ("Form", "Posse-cut rap"),
            ("Voices", "Jude · Paul"),
        ],
        "moves": [
            {"label": "Why a Jude tune here", "text": "Jude “zooms in on false teachers so close you can see they pores”; they creep in unnoticed, twisting grace into a license (Jude 4)."},
            {"label": "Guard the deposit", "text": "Titus says keep doctrine tight; they profess to know God but deny Him in their works (Titus 1:16)."},
            {"label": "Godliness for gain", "text": "1 Timothy 6 exposes the love of money dressed as ministry — a “form of godliness” with no power (1 Timothy 6:5; 2 Timothy 3:5)."},
            {"label": "Itching ears", "text": "2 Timothy 4: people gather teachers who say what they want to hear; same cross denied, different century (2 Timothy 4:3–4)."},
        ],
        "terms": [
            {"term": "“Jude verse four”", "gloss": "The hinge text: “certain people have crept in unnoticed… who pervert the grace of our God into sensuality.”"},
            {"term": "“a form of godliness”", "gloss": "2 Timothy 3:5 — “having the appearance of godliness but denying its power.”"},
            {"term": "“itching ears”", "gloss": "2 Timothy 4:3 — hearers who accumulate teachers “to suit their own passions.”"},
            {"term": "godliness for profit", "gloss": "1 Timothy 6:5 — those who imagine “godliness is a means of gain.”"},
            {"term": "Titus and Tim", "gloss": "Paul’s pastoral letters to Titus (on Crete) and Timothy (at Ephesus) — the field manuals for guarding sound doctrine."},
        ],
        "discussion": [
            "The song says false teachers “smile wide, shake hands… enslave you with plans.” How do you spot the polite, plausible counterfeit?",
            "“Itching ears gather teachers who say what you wanna hear.” How do our own desires shape who we choose to listen to?",
            "What’s the difference between healthy discernment and a critical, fault-finding spirit?",
        ],
        "contemplation": [
            "Whose teaching are you drawn to mainly because it tells you what you already want to hear?",
            "Where might you be tempted to “lighten the load” of a hard truth?",
            "Is there any way you treat godliness as “a means of gain”?",
        ],
        "kind": "verse",
        "blocks": [
            {"label": "Intro — Spoken", "lines": [
                "Yeah, I know, I know —",
                "This is a First John joint,",
                "So what’s a Jude tune",
                "Doin’ here?",
                "Jude zooms in on false teachers",
                "So close you can see they pores —",
                "And they are poor.",
            ]},
            {"label": "Verse 1", "lines": [
                "Yeah, we bringin’ truth,",
                "No fables, no lies.",
                "Call ’em out — false prophets",
                "Exposed in the light.",
                "They claimin’ they speakin’ wisdom,",
                "But it’s just a disguise.",
                "Act like they’re sent to lead,",
                "But they just lead to lies.",
                "Look at Jude, verse four —",
                "False teachers creep in,",
                "Turnin’ grace to a license,",
                "Man, where do I begin?",
                "They slip through unnoticed,",
                "Smile wide, shake hands.",
                "Say freedom out loud,",
                "But enslave you with plans.",
            ]},
            {"label": "Verse 2", "lines": [
                "Titus warned — keep doctrine tight,",
                "Sound words matter, guard that life.",
                "They claim to know God,",
                "But deny Him in deeds.",
                "All talk, no fruit —",
                "Just pride and greed.",
                "Just like Tim said, chapter three,",
                "A form of godliness, no power to see.",
                "Lovers of self, lovers of gain,",
                "Holy vocabulary, unholy aim.",
                "They don’t tremble at truth,",
                "They market it slick.",
                "Godliness for profit —",
                "That’s a dangerous mix.",
            ]},
            {"label": "Chorus", "lines": [
                "False prophets, false lights,",
                "They lead you astray.",
                "Preach prosperity loud,",
                "But don’t live the way.",
                "Jude already said it —",
                "We keepin’ the faith strong.",
                "Titus and Tim",
                "Show ’em they all dead wrong.",
            ]},
            {"label": "Verse 3", "lines": [
                "First Tim, chapter six —",
                "Love of money exposed.",
                "They preach with a smile,",
                "But their heart’s in their goals.",
                "Teachin’ godliness for gain,",
                "Callin’ greed blessed.",
                "Jesus said beware —",
                "That test don’t pass the test.",
                "Second Tim, four-three —",
                "Yeah, it’s gettin’ real clear.",
                "Itchin’ ears gather teachers",
                "Who say what you wanna hear.",
                "Truth gets heavy,",
                "So they lighten the load.",
                "Same cross denied,",
                "Different century mode.",
            ]},
            {"label": "Chorus", "lines": [
                "False prophets, false lights,",
                "They lead you astray.",
                "Preach prosperity loud,",
                "But don’t live the way.",
                "Jude already said it —",
                "We keepin’ the faith strong.",
                "Titus and Tim",
                "Show ’em they all dead wrong.",
            ]},
            {"label": "Verse 4", "lines": [
                "But I ain’t lettin’ it slide,",
                "I’m standin’ on truth.",
                "Like Paul told Timothy,",
                "Guard your heart — stay proof.",
                "They don’t care for the Word,",
                "Just the fame and the hype.",
                "But I’m holdin’ the gospel,",
                "Keepin’ my soul tight.",
                "From Jude to Titus,",
                "From Tim to now,",
                "Same warnings echo,",
                "Same lies somehow.",
                "False teachers exposed,",
                "Masks fall away.",
                "Light don’t whisper —",
                "It burns through the shade.",
            ]},
            {"label": "Outro", "lines": [
                "So we call ’em out.",
                "We stand firm.",
                "Don’t let ’em twist the truth.",
                "Don’t let ’em burn.",
                "From Jude to Titus —",
                "We keep it real.",
                "False teachers exposed.",
                "Their error revealed.",
            ]},
        ],
        "refs": [
            "Jude 3–4",
            "Titus 1:10–16",
            "1 Timothy 6:3–10",
            "2 Timothy 3:1–5",
            "2 Timothy 4:3–4",
        ],
    },
    {
        "num": 7,
        "title": "Jude",
        "slug": "jude",
        "about": (
            "The faith once for all delivered — Jude exposes the creepers and the "
            "grumblers, but God is able to keep you from stumbling and present you "
            "blameless before His glory."
        ),
        "thesis": (
            "The faith was delivered once for all — and Jude lines the ancient "
            "warnings (Cain, Balaam, Korah) against the creepers and grumblers, "
            "only to land on the doxology: God is able to keep you from stumbling "
            "and present you blameless."
        ),
        "facts": [
            ("Doctrine", "Perseverance · Apostasy · Contending"),
            ("Anchor text", "Jude 1–25"),
            ("Form", "Hard-edged rap"),
            ("Voices", "Jude, the brother of James"),
        ],
        "moves": [
            {"label": "Once for all", "text": "Contend for the faith delivered to the saints; if you drift, you don’t upgrade truth — you abandon the anchor meant to keep you (Jude 3)."},
            {"label": "The hall of warnings", "text": "Egypt, Sodom, Cain’s envy, Balaam’s greed, Korah’s pride — “clouds with no rain, wandering stars” (Jude 5–13)."},
            {"label": "Michael’s restraint", "text": "Even the archangel didn’t revile but said “The Lord rebuke you”; truth doesn’t scream when the Judge is near (Jude 9)."},
            {"label": "Kept by mercy", "text": "Build yourselves up, pray in the Spirit, show mercy; He who began it will keep you blameless before His glory (Jude 20–24)."},
        ],
        "terms": [
            {"term": "“once for all delivered”", "gloss": "Jude 3 — the faith as a fixed deposit handed down, not an evolving thing to be upgraded."},
            {"term": "Cain, Balaam, Korah", "gloss": "Jude’s three archetypes of apostasy: murderous envy (Genesis 4), the prophet-for-hire’s greed (Numbers 22–24), and rebellion against God-given authority (Numbers 16)."},
            {"term": "“wandering stars / clouds without rain”", "gloss": "Jude 12–13 — vivid images of teachers who promise everything and deliver nothing."},
            {"term": "“The Lord rebuke you”", "gloss": "Michael the archangel’s words, disputing over the body of Moses (Jude 9; cf. Zechariah 3:2) — restraint instead of reviling."},
            {"term": "“able to keep you from stumbling”", "gloss": "Jude 24 — the great closing doxology that anchors the chorus."},
        ],
        "discussion": [
            "Jude says to “contend” for the faith and also to “show mercy.” How do you hold earnest defense and mercy together?",
            "Cain, Balaam, Korah — envy, greed, pride. Which is most at work in the church today, and how?",
            "The chorus rests on God keeping us, not us keeping ourselves. How should that change the tone of “contending”?",
        ],
        "contemplation": [
            "Where are you tempted to “upgrade truth” rather than admit you’ve drifted?",
            "Of Cain (envy), Balaam (greed), Korah (pride) — which most exposes your heart right now?",
            "Can you rest today in “kept by mercy, not by fear”?",
        ],
        "kind": "verse",
        "blocks": [
            {"label": "Verse 1", "lines": [
                "Once for all — faith delivered to the saints.",
                "Not new words, just ancient constraints.",
                "If you drift, you don’t upgrade truth,",
                "You abandon the anchor meant to keep you.",
                "Jude on the mic, no counterfeit faith,",
                "Brother of James — exposin’ the fakes.",
                "Creepin’ in church like snakes in grass,",
                "Twistin’ grace for a backstage pass.",
                "They deny the Lord, but the judgment’s near,",
                "Egypt fell — even angels fear.",
                "Sodom burned for its filthy game,",
                "What makes you think you’ll dodge that flame?",
            ]},
            {"label": "Verse 2", "lines": [
                "Dreamers talk loud, reject command,",
                "Boast of the flesh they don’t understand.",
                "Cain’s envy, Balaam’s greed,",
                "Korah’s pride — same ol’ seed.",
                "Clouds with no rain, roots all dead,",
                "Wanderin’ stars, no light ahead.",
                "They mock what they’ve never known,",
                "Instinct-driven, truth disowned.",
                "Grumblers grift for personal gain,",
                "Grace on their lips, no fear of His name.",
            ]},
            {"label": "Chorus", "lines": [
                "They try’n to shake me, but God’s gonna make me stay.",
                "He’s able to keep me from fallin’ away.",
                "Glory and power to Christ always —",
                "Ain’t no one takin’ my praise.",
                "He holds me tight when the crowd betrays,",
                "Mercy and love my anthem plays.",
                "They try’n to shake me, but God’s gonna make me stay —",
                "Forever secure in His ways.",
            ]},
            {"label": "Verse 3", "lines": [
                "Michael fought but kept it clean,",
                "The Lord rebuke you — heaven’s theme.",
                "Power restrained, authority clear,",
                "Truth don’t scream when the Judge is near.",
                "They mock what they’ve never known,",
                "Instinct-driven, truth disowned.",
                "Grumblers grift for personal gain,",
                "Grace on their lips, no fear of His name.",
            ]},
            {"label": "Verse 4", "lines": [
                "But you — build faith, stay awake.",
                "Pray in Spirit for mercy’s sake.",
                "Keep love warm when the culture’s cold,",
                "Don’t let your oil run out — stay bold.",
                "Show mercy, pull ’em from flame,",
                "Hate the stain, still love the name.",
                "He who called you won’t let go,",
                "Stand firm while the mockers show.",
            ]},
            {"label": "Bridge", "lines": [
                "Not by grip, but by His hand.",
                "Not by strength, but by His plan.",
                "Before all time — He stood alone,",
                "Still the King upon the throne.",
                "If He began it, He’ll sustain.",
                "If He called you, He’ll remain.",
                "Kept by mercy, not by fear.",
                "Held secure — the end is clear.",
            ]},
            {"label": "Final Chorus", "lines": [
                "They try’n to shake me, but God’s gonna make me stay.",
                "He’s able to keep me from fallin’ away.",
                "Glory and power to Christ always —",
                "Ain’t no one takin’ my praise.",
                "To the only God our Savior’s name,",
                "Through Jesus Christ — forever reign.",
            ]},
            {"label": "Outro — Spoken", "lines": [
                "Kept…",
                "From stumbling…",
                "Before His glory…",
                "With great joy…",
            ]},
        ],
        "refs": [
            "Jude 1–25",
            "Deuteronomy 32",
            "Genesis 4",
            "Numbers 16",
            "Hebrews 7:25",
        ],
    },
    {
        "num": 8,
        "title": "AntiChrist",
        "slug": "antichrist",
        "about": (
            "The antichrist spirit isn’t horns and smoke — it’s “Christ plus,” the "
            "old serpent’s call to add to the gospel. Hold the line; abide in the "
            "fire till His glory appears."
        ),
        "thesis": (
            "The antichrist spirit isn’t horns and smoke — it’s “Christ plus,” the "
            "old serpent’s call to add to a finished gospel. The command is to "
            "hold the line and abide in the fire till His glory appears."
        ),
        "facts": [
            ("Doctrine", "Discernment · Sufficiency of Christ"),
            ("Anchor text", "1 John 2:18–27"),
            ("Form", "Anthemic rap-rock"),
            ("Voices", "The Apostle John"),
        ],
        "moves": [
            {"label": "Out from us", "text": "“They went out from us” — parasites feeding on true belief from within the holy place itself (1 John 2:19)."},
            {"label": "Many faces, one infection", "text": "Christ plus law, plus fame, plus free will; a god they can “keep clean” (1 John 2:18)."},
            {"label": "Don’t add gold to the blood", "text": "The chorus: “Jesus plus nothing” — the anointing burns in the faithful heart (1 John 2:20, 27; Colossians 2:6–10)."},
            {"label": "The oldest whisper", "text": "“Old things die, let progress fly” — but the oldest Word still shakes the sound; Christ remains, He conquers all (Galatians 1:6–9)."},
        ],
        "terms": [
            {"term": "antichrist", "gloss": "In John’s letters, not a single end-times figure but the spirit of any teaching that denies or dilutes the Son (1 John 2:18, 22)."},
            {"term": "“Christ plus” / adding to Christ", "gloss": "The recurring danger — a “Jesus plus” gospel, which Paul calls “another gospel” and pronounces anathema (Galatians 1:6–9)."},
            {"term": "“from séance to screen”", "gloss": "The song’s sweep of counterfeits across history — from the occult to the algorithm."},
            {"term": "Chronos", "gloss": "Greek for time itself: “Chronos laughs, but saints don’t fade” — the newer is not the truer."},
            {"term": "“Abide in the Lion, ye sons of the Light”", "gloss": "“Sons of light” is 1 Thessalonians 5:5; “the Lion” nods to the Lion of Judah (Revelation 5:5)."},
        ],
        "discussion": [
            "John defines “antichrist” as anything that adds to or subtracts from Christ. What are today’s most respectable “Christ plus” offers?",
            "“They went out from us.” Why does the most dangerous error so often come from inside the church?",
            "The chorus says “Jesus plus nothing.” Where is that hardest to actually live?",
        ],
        "contemplation": [
            "What “plus” are you quietly attaching to Christ — a rule, an achievement, a comfort?",
            "Where do you feel the pull of “newer is truer”?",
            "What would it look like to “hold the line” in your own faith this week?",
        ],
        "kind": "verse",
        "blocks": [
            {"label": "Intro — Spoken", "lines": [
                "Children, the hour is closing in.",
                "The test of antichrists will now begin.",
            ]},
            {"label": "Pre-Verse", "lines": [
                "They went out from us — now we see,",
                "Parasites feed on true belief.",
                "No fang or claw, just cancer’s breath,",
                "They feed on life, excrete death.",
                "False lights burn in cathedral halls,",
                "Each new antichrist, the old serpent’s call.",
            ]},
            {"label": "Pre-Chorus", "lines": [
                "Many voices, one deception.",
                "Many faces, one infection.",
                "From within the holy place,",
                "They put a mask on saving grace.",
            ]},
            {"label": "Chorus", "lines": [
                "Hold the line — abide in the fire.",
                "Don’t bow down to the world’s desire.",
                "Jesus plus nothing — the cry of the true.",
                "The cross is enough — it pushes through.",
                "Hold the line — till His glory appears.",
                "Abide in Christ, not unbelief’s fear.",
            ]},
            {"label": "Verse 1", "lines": [
                "Christ plus law, Christ plus fame,",
                "Christ plus free will — it’s all the same.",
                "From Rome to the desert, from séance to screen,",
                "They sell you a god they can keep clean.",
                "Newer is truer, the age declares,",
                "But the root still lives while the road despairs.",
                "Modern prophets, old disguise,",
                "Trading truth for alibis.",
            ]},
            {"label": "Pre-Chorus", "lines": [
                "One ethos, one design —",
                "To steal His crown, to blur the line.",
                "They preach of light, but dark they bring.",
                "Adding to Christ — a terrible thing.",
            ]},
            {"label": "Chorus", "lines": [
                "Hold the line — abide in the fire.",
                "Don’t add gold to the blood of the Sire.",
                "Stay with the truth you knew from the start.",
                "The anointing burns in the faithful heart.",
                "Hold the line — till the heavens ignite.",
                "Abide in the Lion — ye sons of the Light!",
            ]},
            {"label": "Bridge", "lines": [
                "Hear the whispers, slick and sly:",
                "Old things die — let progress fly.",
                "But roots run deep in sacred ground.",
                "The oldest Word still shakes the sound.",
                "Chronos laughs, but saints don’t fade.",
                "The truth you knew — the price He paid.",
                "The beast may rise, the stars may fall,",
                "But Christ remains — He conquers all!",
            ]},
            {"label": "Outro — Chant", "lines": [
                "Don’t grow bored",
                "With what you had from beginning.",
                "No new Christs, the original is winning.",
                "To add something new is deadly sinning.",
            ]},
        ],
        "refs": [
            "1 John 2:18–27",
            "Matthew 24:4–5",
            "Galatians 1:6–9",
            "Colossians 2:6–10",
        ],
    },
    {
        "num": 9,
        "title": "Bread of Judas",
        "slug": "bread-of-judas",
        "about": (
            "Judas ran on grace he refused — fed by the very Lord he would "
            "betray. The oldest story: mistaking the Giver for the gifts, from "
            "Eden to the upper room."
        ),
        "thesis": (
            "Judas ran on grace he refused — his very feet washed and his body "
            "fed by the Lord he was about to betray. It’s the oldest story: "
            "mistaking the Giver for the gifts, from Eden to the upper room."
        ),
        "facts": [
            ("Doctrine", "Common grace · Apostasy · Depravity"),
            ("Anchor text", "John 13:1–30"),
            ("Form", "Cinematic storytelling rap"),
            ("Voices", "—"),
        ],
        "moves": [
            {"label": "Fed on the way to betray", "text": "In the upper room Judas’ body ran on “gifted energy,” and the feet he walked away on had just been washed by the Lord (John 13:2, 26–30)."},
            {"label": "The bread testified", "text": "That meal was a mirror, not a mistake; “the bread said Repent, Judas heard Get paid” (John 13:27)."},
            {"label": "Giver vs. gifts", "text": "The Eden pattern: loving the gold God gave, worshipping the gift — Romans 1’s great exchange (Romans 1:21–25; Genesis 3)."},
            {"label": "God in between", "text": "The long story of grace abused, until the Creator gets fixed to a tree — “guilty but pardoned, judged and redeemed” (Hebrews 6:4–6)."},
        ],
        "terms": [
            {"term": "the bread of Judas", "gloss": "The morsel Jesus dipped and handed Judas at the Last Supper (John 13:26) — the song’s central image of grace given to one who refused it."},
            {"term": "“Four-D chess”", "gloss": "A slang image for God’s sovereignty: His mercy feeding His own foe is a move “the world don’t know.”"},
            {"term": "“Romans One wreck”", "gloss": "Romans 1:21–25 — exchanging the Creator’s glory for created things, the engine of all idolatry."},
            {"term": "“the gold God gave ’em… worshippin’ heathens”", "gloss": "The golden calf (Exodus 32) and Israel craving the chains — the recurring Giver-vs-gifts pattern."},
            {"term": "“Grace fed him, but love never entered him”", "gloss": "The chilling outro: common grace received without saving grace (cf. Hebrews 6:4–6)."},
        ],
        "discussion": [
            "Judas got every privilege — taught, fed, feet washed — and still betrayed Christ. What does that say about privilege versus a changed heart?",
            "“Mistaking the Giver for the gifts.” Where do we worship God’s good gifts instead of God?",
            "How do we hold “God’s mercy feeding His foe” (sovereignty) together with Judas’s real guilt?",
        ],
        "contemplation": [
            "Which of God’s gifts are you most tempted to love more than the Giver?",
            "Have you ever “used God’s kindness as travel funds to flee the Light”?",
            "“Grace fed him, but love never entered him.” How would you know the difference in yourself?",
        ],
        "kind": "verse",
        "blocks": [
            {"label": "Intro — Spoken", "lines": [
                "You ever think about",
                "the bread of Judas?",
                "It’s all right there",
                "in John thirteen.",
            ]},
            {"label": "Verse 1", "lines": [
                "The upper room — a place provided by God,",
                "The disciples assembled, but one is a fraud.",
                "He’s gonna rat on the Lord ’neath the olive trees,",
                "But before he goes out — he needs some calories.",
                "That’s crazy — God’s mercy feedin’ His foe,",
                "Four-D chess that the world don’t know.",
                "And it gets wilder — think about his feet:",
                "The body of Judas ran on gifted energy.",
                "The feet he walked away on were just recently cleaned",
                "By the Lord — yeah, sit with that scene.",
                "It’s insane.",
                "Romans One wreck like a derailed train,",
                "Given light, but he loved the shade,",
                "Fed by grace on the way to betray.",
            ]},
            {"label": "Chorus", "lines": [
                "Stealin’ gifts from the Giver,",
                "Blessings hijacked by the sinner.",
                "Judas was a man who needs ’em,",
                "So he can bite the hand that feeds him.",
                "Stealin’ gifts from the Giver,",
                "Blessings hijacked by the sinner.",
            ]},
            {"label": "Verse 2", "lines": [
                "That bread wasn’t neutral — it testified.",
                "Every bite screamed the love he decided to deny.",
                "Same hands that broke it would soon be bound.",
                "Same face that smiled would wear a thorny crown.",
                "The problem wasn’t hunger — it was love he refused.",
                "Traded grace for silver, yeah, he lost big too.",
                "Light hit his eyes, but he stayed in the shade.",
                "Greed playin’ with fire — and he got played.",
                "That meal was a mirror, not a mistake.",
                "Judgment delayed — not erased.",
                "The bread said, Repent.",
                "Judas heard, Get paid.",
                "Same gift offered — different way.",
            ]},
            {"label": "Chorus", "lines": [
                "Stealin’ gifts from the Giver,",
                "Blessings hijacked by the sinner.",
                "Judas was a man who needs ’em,",
                "So he can bite the hand that feeds him.",
                "Stealin’ gifts from the Giver,",
                "Blessings hijacked by the sinner.",
            ]},
            {"label": "Bridge", "lines": [
                "Some folks still eat and never stay,",
                "Take the gifts, then walk away.",
                "Use God’s kindness as travel funds",
                "To flee the Light ’til life is done.",
            ]},
            {"label": "Verse 3 — Double-Time", "lines": [
                "It’s always been the same since the Garden of Eden,",
                "People mixin’ up the Giver with the gifts He was feedin’.",
                "Obedient in chains, but they wander with freedom,",
                "Loved the gold God gave ’em, started worshippin’ heathens.",
                "Fresh out the garden, they reach for the fruit,",
                "Wanted wisdom without trust — now they naked in truth.",
                "Cain brought an offering, but his heart wasn’t right,",
                "So he murdered his brother just to quiet the light.",
                "Noah preached rain while they laughed at the skies,",
                "Built an ark outta faith while the world told him lies.",
                "Saved by the wood while the proud ones drowned,",
                "Same story — different stage, same sin goin’ round.",
                "Israel freed from the whips of the land,",
                "But they cried for the chains when the desert got bland.",
                "Used the gold God gave ’em, melted mercy to calves,",
                "Wanted gods they could touch, not a voice with a plan.",
                "Empires rose, then they crumbled to dust,",
                "Babel tech used to invest in moth and rust.",
                "The Jews arrested the truth ’cause He wouldn’t trust them,",
                "The Creator got fixed to a cross ’cause our wires were crossed.",
                "Didn’t fix it with force — He got fixed to a tree,",
                "’Cause that’s how He sees you, and that’s how He sees me.",
                "Guilty but pardoned, judged and redeemed,",
                "Same old story — God in between",
                "Heaven and earth — mediating.",
            ]},
            {"label": "Chorus", "lines": [
                "Stealin’ gifts from the Giver,",
                "Blessings hijacked by the sinner.",
                "Judas was a man who needs ’em,",
                "So he can bite the hand that feeds him.",
                "Stealin’ gifts from the Giver,",
                "Blessings hijacked by the sinner.",
            ]},
            {"label": "Outro — Spoken", "lines": [
                "Grace fed him.",
                "But love never entered him.",
            ]},
        ],
        "refs": [
            "John 13:1–30",
            "Romans 1:21–25",
            "Genesis 3",
            "Matthew 26:14–16",
            "Hebrews 6:4–6",
        ],
    },
    {
        "num": 10,
        "title": "One Road Home (The Prodigal)",
        "slug": "one-road-home",
        "about": (
            "A thousand roads lead into the wilderness, but one road leads home. "
            "The prodigal’s turn: to God is to be integrated; away from Him is to "
            "disintegrate."
        ),
        "thesis": (
            "A thousand roads lead into the wilderness, but one road leads home. "
            "The prodigal’s turning point: to turn toward God is to be "
            "integrated; to turn away is to disintegrate."
        ),
        "facts": [
            ("Doctrine", "Repentance · Prodigal grace"),
            ("Anchor text", "Luke 15:11–32"),
            ("Form", "Cinematic worship-pop"),
            ("Voices", "—"),
        ],
        "moves": [
            {"label": "The winding highways", "text": "Chasing a thousand dreams, sure that freedom lived in choosing every path — but every trail kept breaking (Luke 15:13–16)."},
            {"label": "Caught in the turning", "text": "“You caught me in the turning, wounded hands set me in place” — the Father runs to meet the returning son (Luke 15:20)."},
            {"label": "Integrated vs. disintegrated", "text": "The chorus’s thesis: turn to God and be made whole; turn away and fall to pieces (Jeremiah 2:13)."},
            {"label": "Remade", "text": "“You spoke my name with kindness, and the chaos took its form” — reconciliation through the wounded hands (Colossians 1:19–22)."},
        ],
        "terms": [
            {"term": "the prodigal", "gloss": "Luke 15:11–32; “prodigal” means recklessly wasteful — describing the squandered inheritance long before it became a byword for the returning son."},
            {"term": "broken cisterns", "gloss": "Jeremiah 2:13 — forsaking the fountain of living water to dig cracked cisterns that hold none. “All the cisterns cracked inside.”"},
            {"term": "integrated / disintegrated", "gloss": "The song’s key contrast: a self gathered and whole around God, versus a self literally coming apart — “pieces on the pavement, fragments in the storm.”"},
            {"term": "“wounded hands set me in place”", "gloss": "The Father’s embrace pictured through the crucified, risen hands of Christ."},
            {"term": "“one road”", "gloss": "The exclusivity of the way home (John 14:6) set against “a thousand scattered, broken roads.”"},
        ],
        "discussion": [
            "The song equates turning from God with “disintegration.” Where do you see that fragmentation in a wandering life or culture?",
            "The Father runs while the son is “still a long way off.” How should that shape how a church receives people who come back?",
            "“Freedom lived in choosing every path” turned out to be bondage. How does our culture sell that lie?",
        ],
        "contemplation": [
            "Which “winding highway” have you mistaken for freedom?",
            "Where do you sense disintegration — coming apart — that only turning home would heal?",
            "Can you hear the Father “speak your name with kindness” today?",
        ],
        "kind": "verse",
        "blocks": [
            {"label": "Verse 1", "lines": [
                "I’ve walked the winding highways,",
                "I’ve chased a thousand dreams.",
                "Thought freedom lived in choosing",
                "Every path that promised me.",
                "But every trail kept breaking,",
                "Every promise came undone —",
                "Till I heard a quiet whisper,",
                "Come on home, my son.",
            ]},
            {"label": "Pre-Chorus", "lines": [
                "I’d been spinning into pieces,",
                "Falling further from Your face.",
                "But You caught me in the turning,",
                "Wounded hands set me in place.",
            ]},
            {"label": "Chorus", "lines": [
                "One road leads home —",
                "And a thousand roads lead into the wilderness.",
                "I’ve traveled both,",
                "And I know the truth that wandering taught me best:",
                "Turn to God — be integrated.",
                "Turn away — disintegrated.",
                "A thousand scattered, broken roads,",
                "But one road leads home.",
                "One road leads home.",
            ]},
            {"label": "Verse 2", "lines": [
                "I chased the winds of pleasure,",
                "Let my hungers be my guide.",
                "But every gain was hollow,",
                "All the cisterns cracked inside.",
                "Yet You were steady, patient,",
                "Tracing mercy through my loss —",
                "Till my broken pieces gathered",
                "At the shadow of Your cross.",
            ]},
            {"label": "Pre-Chorus", "lines": [
                "In the light I found my center,",
                "In Your love my soul aligned.",
                "You remade the man who wandered —",
                "You restored my heart and mind.",
            ]},
            {"label": "Chorus", "lines": [
                "One road leads home —",
                "And a thousand roads lead into the wilderness.",
                "I’ve tasted both,",
                "And I know the truth that wandering taught me best:",
                "Turn to God — be integrated.",
                "Turn away — be disintegrated.",
                "A thousand scattered, broken roads,",
                "But one road leads home.",
                "One road leads home.",
            ]},
            {"label": "Bridge", "lines": [
                "I was pieces on the pavement,",
                "I was fragments in the storm.",
                "But You spoke my name with kindness —",
                "And the chaos took its form.",
                "Now my heart beats to a rhythm,",
                "To Your truth in every tone.",
                "One road starts in surrender…",
                "And that road leads home.",
            ]},
            {"label": "Final Chorus", "lines": [
                "One road leads home —",
                "And a thousand roads lead into the wilderness.",
                "I’ve tasted both,",
                "And I know the truth that wandering taught me best:",
                "Turn to God — be integrated.",
                "Turn away — be disintegrated.",
                "A thousand scattered, broken roads,",
                "But one road leads home.",
                "One road leads home.",
            ]},
            {"label": "Outro", "lines": [
                "One road leads home…",
                "And I’m walking it at last.",
            ]},
        ],
        "refs": [
            "Luke 15:11–32",
            "Jeremiah 2:13",
            "Isaiah 55:6–7",
            "Colossians 1:19–22",
        ],
    },
    {
        "num": 11,
        "title": "Noel",
        "slug": "noel",
        "about": (
            "The deep descent of the Creator born of the creature — clasping the "
            "Ancient of Days as the Infant of Days. R.G. Lee’s “from the glory "
            "place to the gory place” framing the old carol."
        ),
        "thesis": (
            "The Creator was born of the creature — the One who rested motherless "
            "on the Father’s bosom now rests fatherless on a woman’s. Because we "
            "cannot ascend to Him, He descended, all the way from the glory place "
            "to the gory place."
        ),
        "facts": [
            ("Doctrine", "Incarnation · Humiliation of Christ"),
            ("Anchor text", "Luke 2 · John 1 · Philippians 2"),
            ("Form", "Spoken-word + carol"),
            ("Voices", "R.G. Lee · trad. carol"),
        ],
        "moves": [
            {"label": "The deep descent", "text": "Clasping the Ancient of Days become the Infant of Days — from the throne to the tree, the glory place to the gory place (Philippians 2:5–8)."},
            {"label": "Humility and glory joined", "text": "Bethlehem: no room for Him who made all rooms; humility and glory in their extremes meet in a manger (Luke 2:7)."},
            {"label": "The First Noel", "text": "The old carol carries the shepherds, the star, the wise men — “born is the King of Israel” (Luke 2:8–20; Matthew 2)."},
            {"label": "He descends to us", "text": "“Because we cannot ascend to Him, He descends” — the dawn of mercy in the descent (John 1:14; Hebrews 2:14–18)."},
        ],
        "terms": [
            {"term": "R.G. Lee · “from the glory place to the gory place”", "gloss": "Robert G. Lee (1886–1978), Southern Baptist preacher famous for his sermon “Payday Someday.” The spoken intro and outro adapt his meditation on the incarnation."},
            {"term": "Ancient of Days / Infant of Days", "gloss": "“Ancient of Days” is God in Daniel 7:9, 13; the paradox is that the eternal God became an infant of days."},
            {"term": "“The First Noel”", "gloss": "A traditional English carol (first published 1823), public domain. “Noël” is from the Latin natalis — “birth.”"},
            {"term": "the humiliation of Christ", "gloss": "The descent of Philippians 2:5–8 — “He emptied Himself… even death on a cross.”"},
            {"term": "“He descends to us”", "gloss": "The logic of the incarnation (John 1:14): God comes down because we cannot climb up."},
        ],
        "discussion": [
            "R.G. Lee piles up the contrasts — “throne to the tree,” “coronation to the curse.” Why does Christmas need Good Friday to be understood?",
            "“No room for Him who made all rooms.” Where do we still have no room for Christ?",
            "The carol was sung first to “certain poor shepherds.” What does the audience of the announcement tell us?",
        ],
        "contemplation": [
            "Sit with “the glory place to the gory place.” What does the depth of the descent say about the worth He places on you?",
            "Is there “no room” for Him in some corner of your life this season?",
            "“Because we cannot ascend to Him, He descends to us.” Where do you need to stop climbing and receive?",
        ],
        "attribution": {
            "text": (
                "The spoken intro and outro adapt R.G. Lee’s famous meditation on "
                "the incarnation — “from the glory place to the gory place.” The "
                "sung verses are the traditional carol “The First Noel” (public "
                "domain)."
            ),
            "links": [
                ("About R.G. Lee", "https://en.wikipedia.org/wiki/Robert_G._Lee_(pastor)"),
            ],
        },
        "kind": "verse",
        "blocks": [
            {"label": "Spoken Intro (R.G. Lee)", "lines": [
                "Christ who in eternity rested motherless upon the Father’s bosom and in time rested fatherless upon a woman’s bosom, clasping the Ancient of Days had become the Infant of Days.",
                "What deep descent from the heights of glory to the depths of shame; from the wonders of heaven to the wickedness of earth; from exaltation to humiliation; from the throne to the tree; from dignity to debasement; from worship to wrath; from the halls of heaven to the nails of earth; from the coronation to the curse; from the glory place to the gory place!",
                "In Bethlehem, humility and glory in their extremes were joined. Born in a stable! Cradled in a cattle trough! Wrapped in swaddling clothes of poverty! No room for Him who made all rooms! Not place for Him who made and knows all places!",
                "Oh, deep humiliation of the Creator – born of the creature, woman! But in His descent was the dawn of mercy. Because we cannot ascend to Him, He descends to us.",
            ]},
            {"label": "The First Noel (traditional lyrics)", "lines": [
                "The first Noel the angel did say",
                "Was to certain poor shepherds",
                "In fields as they lay;",
                "In fields where they lay tending their sheep,",
                "On a cold winter’s night that was so deep.",
            ]},
            {"label": None, "lines": [
                "Noel, Noel, Noel, Noel,",
                "Born is the King of Israel.",
            ]},
            {"label": None, "lines": [
                "They lookèd up and saw a star",
                "Shining in the east, beyond them far;",
                "And to the earth it gave great light,",
                "And so it continued both day and night.",
            ]},
            {"label": None, "lines": [
                "And by the light of that same star",
                "Three wise men came from country far;",
                "To seek for a king was their intent,",
                "And to follow the star wherever it went.",
            ]},
            {"label": None, "lines": [
                "This star drew nigh to the northwest,",
                "Over Bethlehem it took its rest;",
                "And there it did both stop and stay,",
                "Right over the place where Jesus lay.",
            ]},
            {"label": None, "lines": [
                "Then did they know assuredly",
                "Within that house the King did lie;",
                "One entered it them for to see,",
                "And found the Babe in poverty.",
            ]},
            {"label": None, "lines": [
                "Then entered in those wise men three,",
                "Full reverently upon the knee,",
                "And offered there, in His presence,",
                "Their gold and myrrh and frankincense.",
            ]},
            {"label": None, "lines": [
                "Between an ox stall and an ass,",
                "This Child truly there He was;",
                "For want of clothing they did Him lay",
                "All in a manger, among the hay.",
            ]},
            {"label": None, "lines": [
                "Then let us all with one accord",
                "Sing praises to our heav’nly Lord;",
                "That hath made Heav’n and earth of naught,",
                "And with His blood mankind hath bought.",
            ]},
            {"label": None, "lines": [
                "If we in our time shall do well,",
                "We shall be free from death and hell;",
                "For God hath prepared for us all",
                "A resting place in general.",
            ]},
            {"label": "Outro (R.G. Lee)", "lines": [
                "What deep descent from the heights of glory to the depths of shame! (AMEN!)",
                "from the wonders of heaven to the wickedness of earth; (AMEN!)",
                "from exaltation to humiliation; from the throne to the tree; (AMEN!)",
                "from dignity to debasement (AMEN!)",
                "from worship to wrath; (AMEN!)",
                "from the halls of heaven to the nails of earth (AMEN!)",
                "from the coronation to the curse; (AMEN!)",
                "from the glory place to the gory place! (AGAIN!)",
                "from the glory place to the gory place! (AGAIN!)",
                "from the glory place to the gory place! (PRAISE JESUS)",
            ]},
        ],
        "refs": [
            "Luke 2:1–20",
            "John 1:1–14",
            "Philippians 2:5–11",
            "Isaiah 9:6–7",
            "Hebrews 2:14–18",
        ],
    },
]
