# -*- coding: utf-8 -*-
"""
Roots of Reason — album data.

Each song carries: track number, display title, url slug, the source .wav in
~/Downloads (best-guess mapping — Chris to confirm), a short "About" note drawn
from the song's own lyrics, the verbatim lyric blocks, and the verbatim
Scripture-reference footnotes exactly as printed in the booklet.

`kind` is "verse" (stanzas of lines) or "prose" (teaching paragraphs).
Superscript footnote markers are dropped from the lyric body for readability;
the full numbered reference list is preserved under `refs`.
"""

ALBUM = {
    "title": "Roots of Reason",
    "slug": "roots-of-reason",
    "order": 2,
    "tagline": "A Theology-in-Song Booklet · Lyrics & Scripture",
    "blurb": (
        "Reformed theology set to roots reggae — the cave of Plato, the dilemma "
        "of Euthyphro, the keys of the apostle, and the empty tomb, all carried "
        "on a one-drop riddim."
    ),
    "cover": "/assets/roots-of-reason/cover.jpg",
    "audio_prefix": "roots-of-reason",
    # No theme override — the base CSS palette IS Roots of Reason (green/gold).
    "theme": None,
    "episode": {
        "order": 7,
        "title": "Roots of Reason — the whole album, sung and explained",
        "guid": "utr-roots-of-reason-2026-07-22",
        "pubDate": "Tue, 21 Jul 2026 12:00:00 -0500",
        "duration": "1:06:43",
        "length": 96192886,
        "audio_url": "https://sermons-cdn.sermonsteward.com/uncle-theology/podcast/roots-of-reason.mp3",
        "image": "https://sermons-cdn.sermonsteward.com/uncle-theology/podcast/roots-of-reason-art.jpg",
        "summary": (
            "Roots of Reason played end to end — Reformed theology set to roots reggae — with a short "
            "spoken intro before every song. Cruciform power before Pilate, the two Adams and true "
            "dominion, Isaiah's thrice-holy vision, the Euthyphro dilemma, Plato's cave as the new "
            "birth, suffering under God's sovereignty, the apostles' hard road, the cage of "
            "autonomy, worship as warfare, the bodily resurrection, the empty tomb of Matthew 28, "
            "and the nations streaming in."
        ),
        "chapters": [
            ("0:00", "Intro — Don't Fight Like the World"),
            ("0:55", "Don't Fight Like the World"),
            ("4:28", "Intro — True Dominion for a Fake Dime"),
            ("5:04", "True Dominion for a Fake Dime"),
            ("10:39", "Intro — Thrice Holy"),
            ("11:25", "Thrice Holy"),
            ("15:02", "Intro — Euthyphro Rocksteady"),
            ("15:42", "Euthyphro Rocksteady"),
            ("19:19", "Intro — Playing with Plato"),
            ("19:57", "Playing with Plato"),
            ("25:38", "Intro — What Christ is Doing in Me"),
            ("26:19", "What Christ is Doing in Me"),
            ("31:44", "A word from our sponsor — Providence Community Church"),
            ("32:02", "Intro — Acts of the Apostles"),
            ("32:40", "Acts of the Apostles"),
            ("36:44", "Intro — Freebird's Cage"),
            ("37:24", "Freebird's Cage"),
            ("42:28", "Intro — Worship is the Warfare"),
            ("43:15", "Worship is the Warfare"),
            ("48:46", "Intro — Solid Ground"),
            ("49:22", "Solid Ground"),
            ("54:15", "Intro — Matthew 28"),
            ("54:55", "Matthew 28"),
            ("61:31", "Intro — Nations Gonna Come"),
            ("62:18", "Nations Gonna Come"),
        ],
    },
}

SONGS = [
    {
        "num": 1,
        "title": "Don't Fight Like the World",
        "slug": "dont-fight-like-the-world",
        "wav": "Don't Fight Like the World (Reggae Sound System Mix).wav",
        "about": (
            "On the temptation to grab the reins when life turns chaotic — and "
            "the gentle, cruciform way Christ refused to fight like the world."
        ),
        # ── Teaching aids (mockup layer; song-level analogue of the Sermon
        #    Steward sermon artifacts). Only song 1 is populated for now. ──
        "thesis": (
            "When life feels out of control, our instinct is to seize the reins — "
            "but Christ shows that real power is exercised through cruciform "
            "submission. The crown comes by way of the cross, not by fighting "
            "like the world."
        ),
        "facts": [
            ("Doctrine", "Sanctification · Suffering"),
            ("Anchor text", "1 Peter 2–3"),
            ("Form", "Roots reggae · sound-system mix"),
            ("Voices", "Paul Tripp · Martyn Lloyd-Jones"),
        ],
        "moves": [
            {
                "label": "The urge to take the wheel",
                "text": "Peter writes to citizens, servants, and wives under unjust authority — all sharing one temptation: to grab control. Anxiety is smoke that reveals where our trust really rests.",
            },
            {
                "label": "Ordering the cosmos",
                "text": "The Greek cosmos means both “order” and “adornment.” We’re tempted to arrange the exterior — clothes, rules, food — while the inner self crumbles. True beauty is the hidden person of the heart.",
            },
            {
                "label": "Tracing the stencil",
                "text": "Christ left a hypogramos — a tracing-pattern — for us to follow. Hanging on the cross with absolute might, He didn’t pick a fight, didn’t revile, didn’t call the angels. He entrusted Himself to the Father.",
            },
            {
                "label": "Crown through cross",
                "text": "Humiliation comes first, then exaltation. The gentle, quiet spirit is the believer’s weapon; casting our cares on the Lord and trusting His sovereignty is how the battle is actually won.",
            },
        ],
        "terms": [
            {"term": "hypogramos", "gloss": "Greek for a child’s tracing-stencil. 1 Peter 2:21 says Christ left us a “pattern” to trace — we follow the lines of His steps."},
            {"term": "cosmos", "gloss": "Carries both “order” and “adornment.” The song plays on ordering the heart versus merely decorating the exterior (1 Peter 3:3–4)."},
            {"term": "“Thanos-snapped Pilate”", "gloss": "A pop-culture image: Christ had the power to erase Pilate in an instant but withheld it — “you would have no authority unless it were given from above” (John 19:11)."},
            {"term": "Paul Tripp", "gloss": "Counselor-author quoted for the line that anxiety is the “dangerous delusion” of thinking we are sovereign."},
            {"term": "Martyn Lloyd-Jones", "gloss": "The “fullback theologian” — a reliable voice Oswald leans on to check his exegesis."},
        ],
        "discussion": [
            "Peter writes to people under unjust authority. Where do believers today feel that same pull to “grab the reins,” and what does faithfulness look like instead?",
            "Christ “didn’t pick a fight,” though He had absolute might. How does His restraint at the trial reshape what real strength looks like?",
            "What does it look like for a community to “fight like the Christian fights” — to lay down earthly weapons together?",
        ],
        "contemplation": [
            "Where are you most tempted to “take the wheel” when life feels chaotic? What does that reveal about where your trust actually rests?",
            "Where are you tempted to “fake the cosmos” — to order the exterior while the inner self crumbles?",
            "What would it look like this week to “put down your earthly weapons”?",
        ],
        "kind": "verse",
        "blocks": [
            [
                "Yeah, let's talk about the urge to take the wheel,",
                "When life gets chaotic and you hate the way it feels.",
                "Peter wrote to citizens, servants, and wives,",
                "Who faced unjust leaders making a mess of their lives.",
                "Three groups, one problem, and a shared temptation,",
                "To reach for control and manipulate the situation.",
                "Paul Tripp said it bluntly, it's a dangerous delusion,",
                "Thinking we are sovereign while living in our own illusion.",
                "Anxiety is smoke, revealing what we really trust,",
                "As we grab for the reins when our idols turn to dust.",
                "We all struggle with “daddy issues,” every single one,",
                "Doubting God is truly good when the damage has been done.",
            ],
            [
                "Don't trust in the chariots, don't trust in the horses,",
                "Trying to fix the chaos with your own external forces.",
                "We order the cosmos in the hidden person of the heart,",
                "Imperishable beauty is the place we gotta start.",
                "Entrust your soul to the God who judges right,",
                "Put down your earthly weapons and learn how the Christian",
                "fights.",
            ],
            [
                "The ancients used the word cosmos to talk about the stars,",
                "But also for the makeup that covers up our scars.",
                "It means to put in order, to organize the nest,",
                "A creational instinct when our spirits are stressed.",
                "But women and men take a shortcut round the soul,",
                "Using clothes, rules, and food as a weapon of control.",
                "If your external physical cosmos looks pristine,",
                "But internally you're crumbling, you know exactly what I",
                "mean.",
                "You can't fake it with your kids, they will notice the dry rot,",
                "If you don't submit your spirit to the Sovereign God we've",
                "got.",
            ],
            [
                "Don't trust in the chariots, don't trust in the horses,",
                "Trying to fix the chaos with your own external forces.",
                "We order the cosmos in the hidden person of the heart,",
                "Imperishable beauty is the place we gotta start.",
                "Entrust your soul to the God who judges right,",
                "Put down your earthly weapons and learn how the Christian",
                "fights.",
            ],
            [
                "We're called to trace the stencil, the hypogramos lines,",
                "Following the footprints of the Maker of the skies.",
                "From a baby to the Jordan, to Gethsemane's mud,",
                "Where the footprints in the dirt get mingled with His blood.",
                "Hanging on the cross, He had absolute might,",
                "Could have Thanos-snapped Pilate, but He didn't pick a fight.",
                "He didn't call the angels, didn't threaten or revile,",
                "He submitted to the Father as He faced a rigged trial.",
                "He knew that human power is just granted from above,",
                "So He carried out the mission out of covenantal love.",
            ],
            [
                "Yeah, the crown doesn't come without the cross that we",
                "bear,",
                "Humiliation comes first, then exaltation is there.",
                "Don't fight like the world, don't rely on your pride,",
                "Let a gentle, quiet spirit be your ultimate guide.",
                "Cast your cares on the Lord, let Him handle the test,",
                "Because trusting in His sovereignty is how we win this quest.",
            ],
        ],
        "refs": [
            "1. 1 Peter 2:13–17; 2:18–25; 3:1–7",
            "2. 1 Peter 5:7; Matthew 6:25–34",
            "3. Psalm 20:7",
            "4. 1 Peter 3:3–4",
            "5. 1 Peter 4:19",
            "6. 2 Corinthians 10:3–4",
            "7. 1 Peter 2:21",
            "8. Matthew 3:13–17; 26:36–39",
            "9. Matthew 26:53",
            "10. 1 Peter 2:23",
            "11. John 19:11",
            "12. 1 Peter 5:6; Philippians 2:8–9",
            "13. 1 Peter 3:3–4",
            "14. 1 Peter 5:7",
        ],
    },
    {
        "num": 2,
        "title": "True Dominion for a Fake Dime",
        "slug": "true-dominion-for-a-fake-dime",
        "wav": "Fake Dime Dominion (Melodic Reggae Cut).wav",
        "about": (
            "Adam traded his God-given dominion to keep his bride; the second "
            "Adam kept dominion by laying down His life — and won the bride back."
        ),
        "thesis": (
            "Adam forfeited his God-given dominion because he loved his bride "
            "more than his Maker; the second Adam kept dominion by loving the "
            "Father first and laying down His life — and so won the bride back."
        ),
        "facts": [
            ("Doctrine", "Headship · Ordered loves · Typology"),
            ("Anchor text", "1 Timothy 2 · Genesis 3"),
            ("Form", "Melodic reggae cut"),
            ("Voices", "The early church fathers"),
        ],
        "moves": [
            {"label": "The fake dime", "text": "A word to Timothy: the order of authority is creational, not cultural — Adam formed first, Eve deceived (1 Timothy 2:12–14; Genesis 2:7)."},
            {"label": "Why Adam fell", "text": "The fathers’ reading: Adam ate from fear of the “lonesome load” of losing his bride — putting wife above Maker. An ordered love made foul (Genesis 3:6; Matthew 10:37)."},
            {"label": "The second-Adam scene", "text": "In Gethsemane, Christ loved the bride but loved the Father first, and refused the serpent’s wilderness offer to “skip the cross” (Matthew 4:8–10; John 10:18)."},
            {"label": "Dominion restored", "text": "Because He wouldn’t trade, He walked out of the tomb “with the keys and the bride” — true dominion bought back at a high price (Revelation 1:18; Ephesians 5:25–27)."},
        ],
        "terms": [
            {"term": "true dominion", "gloss": "The creational mandate to guard and keep, given in the garden (Genesis 1–2; Genesis 2:15)."},
            {"term": "fake dime", "gloss": "The counterfeit trade — surrendering a God-given calling to secure a lesser love."},
            {"term": "ordered love foul", "gloss": "Augustine’s ordo amoris: loving good things in the wrong order. Loving wife above God disorders the love (Matthew 10:37)."},
            {"term": "second Adam", "gloss": "Christ as the last Adam who succeeds where the first failed (1 Corinthians 15:45; Romans 5:14)."},
            {"term": "“Get behind Me”", "gloss": "Christ’s rebuke of the satanic shortcut that would skip the cross (Matthew 4:10; 16:23)."},
        ],
        "discussion": [
            "The song says a genuinely good love (Adam’s for Eve) became idolatry when it outranked his love for God. How can a good thing become a “fake dime”?",
            "How does Christ’s refusal of the serpent’s shortcut reframe what faithful leadership actually costs?",
            "Where does our culture pressure people to “trade dominion” — to abdicate God-given responsibility — and call it wisdom?",
        ],
        "contemplation": [
            "Where are you tempted to trade a God-given responsibility to keep a relationship or comfort — to take “a fake dime”?",
            "“A man who’d sell his God to keep his bride will lose them both.” Where do you need to love God first in order to truly love others?",
            "Check the pocket, brother — is it true dominion, or a counterfeit dime?",
        ],
        "kind": "verse",
        "blocks": [
            [
                "True Dominion, Traded for a Fake Dime",
                "True Dominion, Trader for a Fake Dime",
            ],
            [
                "Dime Dime Dime Dime Dime",
            ],
            [
                "We've been working at this sellout",
                "For such a long time",
                "Its a problem that's old",
                "A tragedy of mankind",
                "To see its seeds in time we rewind",
                "To first century AD",
                "In a word to Timothy",
                "From Paul the apostle",
                "This words gonna jostle",
                "The feelings of feminists",
                "But the word is what it is",
                "So listen and don't get hostile",
            ],
            [
                "I do not permit a woman to teach",
                "Or preach or breach",
                "The ancient design of authority",
                "Built at the start of time",
                "That's not Pauls opinion",
                "And certainly not mine",
                "We're both only tracing",
                "The plan of the divine",
                "This argument isn't cultural",
                "Its creational so lets go back further into time",
            ],
            [
                "Paul says, Adam was made first",
                "And Eve was deceived that's her part in the curse",
                "Adam's sin... is in some sense made worse",
                "You see he didn't buy the serpent's line",
                "He traded true dominion for a fake dime",
            ],
            [
                "The early church fathers thought a lot about this text",
                "The reason Adam sinned left them perplexed",
                "But then some of them began to crack the code",
                "Adam ate the fruit because he feared the lonesome load",
                "Of losing his beloved — and so the story goes",
                "To live in the garden if his bride couldn't stay",
                "So he sold out for a dime on the very same day",
                "Now hear me out, brothers, that's a love that sounds true",
                "But it's idolatry dressed up — getting ultimates confused",
                "Putting wife above Maker is ordered love foul",
                "Adam made his wife an idol and sin to her he bowed",
            ],
            [
                "Now fast-forward the tape to a second-Adam scene",
                "Another garden, another bride, another in-between",
                "But this Man on His knees in Gethsemane sweat",
                "Wasn't trading His Father for a distant second best",
                "He loved her, oh He loved her, more than Adam ever could",
                "But He loved the Father first — that's what makes the love",
                "good",
                "See the serpent came back with the same old dime",
                "Offered kingdoms in the wilderness, said “skip the climb,",
                "Skip the cross, skip the nails, skip the cup You gotta drink,",
                "Just bow one time, just blink, just think —",
                "Let your mother lead you",
                "Let Mary or Martha set the tone",
                "Let one of the pretty damsels",
                "Occupy your loneliness",
                "You can have the bride without the blood on the tree”",
                "But the second Adam said, “Get behind Me”",
                "He wouldn't sell the Father to purchase the wife",
                "So He kept true dominion by laying down His life",
                "And here's the mystery the first Adam missed —",
                "The Man who won't idolize her is the Man who gets blessed",
                "By, covered by, cherished by, kept —",
                "Christ didn't trade, so Christ didn't have to repent",
                "He walked out the tomb with the keys and the bride",
                "True Dominion restored — no fake dime on His side",
            ],
            [
                "So a word to the brothers in the back of the room",
                "You inherited a garden and a guard-it-or-lose",
            ],
            [
                "Don't trade your dominion for a dime, for a wife,",
                "For a job, for a screen, for a quieter life",
                "Don't abdicate the watch then complain when she's tired",
                "Of carrying weight that her shoulders weren't wired",
                "To hold — that's the order that Adam overthrew",
                "When he handed her the headship that was given to you",
                "Love her? Yes — but love the Father more",
                "That's the only love that knows what love is for",
                "A man who'd sell his God to keep his bride in the room",
                "Is a man who'll lose them both at the lip of the tomb",
                "But a man who keeps dominion at the foot of the throne",
                "Is a man who brings his bride to a forever home",
                "So check the pocket, brother, see what's jingling inside",
                "Is it true dominion? Or a counterfeit dime?",
                "The serpent's still selling the same old deal",
                "But a son of the second Adam knows the kingdom is real",
                "Stand at the gate. Stand in the gap. Stand at the door.",
                "That's the dominion you were made and remade for.",
            ],
            [
                "True Dominion,",
                "Bought back at a high price",
                "The second Adam paid it —",
                "Now the bride's alive",
            ],
        ],
        "refs": [
            "1. 1 Timothy 1:2; 2 Timothy 1:2",
            "2. 1 Timothy 2:12",
            "3. 1 Timothy 2:13; Genesis 2:7",
            "4. 1 Timothy 2:14; Genesis 3:16",
            "5. Genesis 3:6",
            "6. Genesis 2:18, 23–24",
            "7. Matthew 10:37",
            "8. 1 Corinthians 15:45; Romans 5:14",
            "9. Luke 22:44; Matthew 26:39",
            "10. Matthew 4:8–10; Luke 4:5–8",
            "11. Matthew 4:10; 16:23",
            "12. John 10:18",
            "13. Revelation 1:18; Ephesians 5:25–27",
            "14. Genesis 2:15",
            "15. Matthew 10:37; Ephesians 5:25",
            "16. Ezekiel 22:30",
            "17. 1 Corinthians 6:20; 1 Peter 1:18–19",
        ],
    },
    {
        "num": 3,
        "title": "Thrice Holy",
        "slug": "thrice-holy",
        "wav": "Thrice Holy (Reggae Reverence Mix).wav",
        "about": (
            "Isaiah's vision in the temple — the burning coal, the cleansed lips, "
            "and the trembling commission to a hard-hearted land."
        ),
        "thesis": (
            "A glimpse of God’s thrice-holy majesty undoes us and then cleanses "
            "us — and the same mercy that burns away our guilt commissions us to "
            "carry His word to a hard-hearted world."
        ),
        "facts": [
            ("Doctrine", "Holiness · Atonement · Calling"),
            ("Anchor text", "Isaiah 6"),
            ("Form", "Reggae reverence mix"),
            ("Voices", "The prophet Isaiah"),
        ],
        "moves": [
            {"label": "The vision", "text": "In the year King Uzziah died, Isaiah sees the Lord high and lifted up, the seraphim crying “holy, holy, holy” (Isaiah 6:1–3)."},
            {"label": "The burning coal", "text": "A seraph presses a coal from the altar to unclean lips; guilt is “bled out,” sin gone like ash from the grate — no remnant, no record (Isaiah 6:6–7)."},
            {"label": "The commission", "text": "“Whom shall I send?” — and a cleansed, untrained but willing voice answers “send me,” bound for a deaf and blind king (Isaiah 6:8–10)."},
            {"label": "The holy seed", "text": "Though cities lie shattered and forests are torn, the stump of the oak still stands — a remnant kept by sovereign command (Isaiah 6:13)."},
        ],
        "terms": [
            {"term": "Thrice Holy (Trisagion)", "gloss": "The seraphim’s threefold “holy” (Isaiah 6:3; Revelation 4:8) — the one attribute of God Scripture lifts to the third degree."},
            {"term": "the coal from the altar", "gloss": "Atonement imagery: cleansing comes from the altar of sacrifice, not from self-effort (Isaiah 6:6–7)."},
            {"term": "the holy seed / the stump", "gloss": "The surviving remnant from which the Messianic line grows even after judgment (Isaiah 6:13)."},
        ],
        "discussion": [
            "Isaiah sees God’s holiness before he sees his own sin. How does a vision of God’s majesty reframe the way we see ourselves?",
            "The coal that cleanses Isaiah comes from the altar. Why does the song insist cleansing is done to us, not by us?",
            "Isaiah’s “send me” comes after his cleansing. How should being forgiven shape a church’s willingness to be sent?",
        ],
        "contemplation": [
            "When did you last glimpse God as “high and lifted up”? How did it change you?",
            "Are you trying to cleanse your own “unclean lips,” or letting the coal do it?",
            "Is your “send me” coming from gratitude for mercy, or from something else?",
        ],
        "kind": "verse",
        "blocks": [
            [
                "In the year that King Uzziah died",
                "I saw the Lord up lifted high",
                "With angels all around the sky",
                "Saying holy, holy, holy",
            ],
            [
                "Then down from the smoke of that terrible place",
                "A seraph flew fast with a fire in his face,",
                "He seized with the tongs from the altar a coal",
                "And pressed it to lips that were sick to the soul.",
                "He burned what was foul and he branded my shame,",
                "Said, “Guilt's been bled out, son — you're clean of the stain.”",
                "My sin hit the floor like an ash from the grate,",
                "No remnant, no record, no lingering weight.",
            ],
            [
                "The doorposts were shaking, the temple still bright,",
                "But mercy burned hotter than terror that night.",
            ],
            [
                "So lift up your voice to the Lord on the throne,",
                "The Holy, thrice Holy, no rival He's known!",
                "His glory fills mountains, fills heaven and earth,",
                "And wretches like me get the spirit's new birth!",
            ],
            [
                "Then thunder rolled out from the smoke-covered throne,",
                "“Whom shall I send?” — and the words shook the stone.",
                "“What man will go carry the message I bring?",
                "What voice will speak truth to a deaf and blind king?”",
                "I trembled, still smoking from mercy's bright spark,",
                "A clean-lipped commission for one from the dark.",
                "“No training, but willing! No map but Thy hand!",
                "Send me through the fire to that hard-hearted land!”",
            ],
            [
                "Though eyes may be blind and though ears may be sealed,",
                "Though hearts be like stone in an unbroken field,",
                "The stump of the oak in the wasteland shall stand —",
                "A holy seed rooted by sovereign command.",
            ],
            [
                "So lift up your voice to the Lord on the throne,",
                "The Holy, thrice Holy, no rival He's known!",
                "Though cities lie shattered and forests be torn,",
                "The Seed yet remains and a kingdom is born!",
            ],
        ],
        "refs": [
            "1. Isaiah 6:1",
            "2. Isaiah 6:2–3",
            "3. Isaiah 6:6",
            "4. Isaiah 6:7",
            "5. Isaiah 6:4",
            "6. Isaiah 6:3; Revelation 4:8",
            "7. Isaiah 6:8",
            "8. Isaiah 6:8",
            "9. Isaiah 6:9–10",
            "10. Isaiah 6:13",
        ],
    },
    {
        "num": 4,
        "title": "Euthyphro Rocksteady",
        "slug": "euthyphro-rocksteady",
        "wav": "Euthyphro Rocksteady.wav",
        "about": (
            "Socrates' old dilemma gets a third answer: goodness isn't above God "
            "or invented by God — it is His very nature, and it has a name."
        ),
        "thesis": (
            "The Euthyphro dilemma is a false choice: goodness is neither a law "
            "above God nor an arbitrary divine whim — it is God’s own eternal "
            "nature. He doesn’t obey the good or invent it; He is it."
        ),
        "facts": [
            ("Doctrine", "Theology proper · Ethics"),
            ("Anchor text", "James 1:17 · Psalm 100:5"),
            ("Form", "Rocksteady"),
            ("Voices", "Socrates · Lewis · Van Til · Frame"),
        ],
        "moves": [
            {"label": "The dilemma", "text": "Socrates corners Euthyphro: is it good because God loves it (a whim), or does God love it because it’s good (a law above Him)? Two horns (Exodus 3:14)."},
            {"label": "The third way", "text": "Goodness is His nature, eternal and true; He doesn’t obey goodness — He is goodness, through and through (James 1:17; Malachi 3:6)."},
            {"label": "The thinkers spar", "text": "Lewis fears a tyrant-God and sides with Socrates; Van Til says that makes God a mere peer to the law; Frame answers that goodness is personal (Romans 1:20)."},
            {"label": "Goodness has a name", "text": "The Problem of Evil assumes a “straight” by which to call things “crooked.” The standard is the One who numbers your hairs (Matthew 10:30; Psalm 34:8)."},
        ],
        "terms": [
            {"term": "Euthyphro Dilemma", "gloss": "From Plato’s Euthyphro: is the holy loved by the gods because it’s holy, or holy because they love it?"},
            {"term": "summum bonum", "gloss": "Latin for “the highest good”; the song asks why evil exists if God is the highest good."},
            {"term": "That Hideous Strength · Maleldil · the Tao", "gloss": "From C.S. Lewis: his novel, his name for God/Christ, and his term (in The Abolition of Man) for the objective moral law."},
            {"term": "Van Til & Frame", "gloss": "Cornelius Van Til and John Frame, Reformed theologians who ground goodness in God’s own character rather than a standard outside Him."},
            {"term": "The Poison of Subjectivism", "gloss": "A C.S. Lewis essay arguing that morality is not merely subjective preference."},
        ],
        "discussion": [
            "Why is “good because God commands it” just as troubling as “God commands it because it’s good”? What third option does the song offer?",
            "If goodness is God’s nature rather than a rule He follows, how does that change the way we trust His commands?",
            "The Problem of Evil assumes a “straight” by which to call things “crooked.” How does evil itself point toward a moral standard?",
        ],
        "contemplation": [
            "Do you treat God’s commands as arbitrary rules to follow, or as the expression of who He is?",
            "Where have you doubted that “God is good… all the time”?",
            "Goodness “has a name.” How does knowing the Good is personal change your obedience?",
        ],
        "further": [
            ("Answering the Euthyphro Dilemma with C.S. Lewis and Cornelius Van Til",
             "https://trendsettercase.wordpress.com/2017/10/31/answering-the-euthyphro-dilemma-with-c-s-lewis-and-cornelius-van-til/"),
        ],
        "kind": "verse",
        "blocks": [
            [
                "Yo, step into the court, Socrates is on the scene.",
                "Questioning Euthyphro, yeah, the air is getting lean.",
                "Is it pious 'cause the gods love it, an arbitrary whim?",
                "Or do they love it 'cause it's holy? Is the standard above them?",
                "That's the Euthyphro Dilemma, two horns on the head.",
                "Either God's a tyrant, or He's following a thread.",
                "Horn A says it's good just 'cause He gave the decree.",
                "Horn B says there's a law that even God's gotta see.",
            ],
            [
                "But it's a false dilemma, there's a third way to go.",
                "Not a law above Him, not a whim from below.",
                "The standard is His nature, eternal and true.",
                "He's not obeying goodness He is goodness, through and",
                "through.",
            ],
            [
                "Now Lewis enters in, he's wary of the “Fiend”.",
                "Rejects that “total depravity” where reason is leaned.",
                "He says if God commanded murder, would murder then be",
                "right?",
                "He sides with Socrates to keep the moral light bright.",
                "But then comes Van Til, with a theological smack.",
                "Says Lewis is too pagan, putting God in the back.",
                "If the law is independent, then God's just a peer.",
                "But Frame says goodness is personal, let's make that clear.",
            ],
            [
                "But it's a false dilemma, there's a third way to go.",
                "Not a law above Him, not a whim from below.",
                "The standard is His nature, eternal and true.",
                "He's not obeying goodness He is goodness, through and",
                "through.",
            ],
            [
                "Look at Mark and Jane, caught in That Hideous Strength.",
                "Escaping from the Macrobes and their twisted length.",
                "The bad guys hate the “Normal,” they want the “objective”",
                "mind.",
                "But Mark finds the “sweet and straight,” leaving “sour and",
                "crooked” behind.",
                "Jane sees the King, and her world gets unmade.",
                "The Tao, the natural law, the price has been paid.",
                "It's not just a rulebook or a cosmic decree.",
                "It's the image of Maleldil that sets the soul free.",
            ],
            [
                "But it's a false dilemma, there's a third way to go.",
                "Not a law above Him, not a whim from below.",
                "The standard is His nature, eternal and true.",
                "He's not obeying goodness He is goodness, through and",
                "through.",
            ],
            [
                "They're tearing it down, calling God to the stand,",
                "Pointing to the evil and the grief in the land.",
                "If He's the summum bonum, why the shadows and the pain?",
                "They deconstruct the King, saying faith is in vain.",
                "But you can't call it “crooked” without a “straight” to",
                "compare.",
                "The Problem of Evil shows the standard is there.",
                "AND THE STANDARD IS THE ONE WHO NUMBERS",
                "YOUR HAIRS",
                "Goodness isn't gone IT HAS A NAME",
            ],
            [
                "So forget the two options, the logic was flawed.",
                "The moral law isn't something separate from God.",
                "He doesn't obey it, and He doesn't just create it.",
                "He instantiates the good, no need to debate it.",
                "From the “Poison of Subjectivity” to the “Fisher King's”",
                "light.",
                "The God of the Scripture is the standard of right.",
                "Goodness is God, and God is good, all the time.",
                "That's the theological truth in this lyrical rhyme.",
            ],
        ],
        "refs": [
            "1. Psalm 119:68; Exodus 3:14",
            "2. Mark 10:18; Luke 18:19",
            "3. James 1:17",
            "4. Romans 1:20; 2:14–15",
            "5. Matthew 10:30; Luke 12:7",
            "6. James 1:17; Malachi 3:6",
            "7. Psalm 100:5; 34:8; Nahum 1:7",
        ],
    },
    {
        "num": 5,
        "title": "Playing with Plato",
        "slug": "playing-with-plato",
        "wav": "Playing with Plato!.wav",
        "about": (
            "Plato's cave read through the gospel: the prisoners chained to "
            "shadows, the one man freed by a covenant light, and the call to "
            "walk out of the sin-bound dark."
        ),
        "thesis": (
            "Plato’s cave is a picture of sin: humanity chained to shadows, "
            "mistaking lies for reality — until the Lord, the true Sun, frees a "
            "prisoner by sovereign covenant light and sends him back to call "
            "others out."
        ),
        "facts": [
            ("Doctrine", "Depravity · Regeneration · Calling"),
            ("Anchor text", "2 Corinthians 4 · Isaiah 42"),
            ("Form", "Roots reggae"),
            ("Voices", "Plato · Charles Wesley"),
        ],
        "moves": [
            {"label": "The cave", "text": "Prisoners chained from youth stare at shadows cast by a flickering fire — a counterfeit world where sin clouds the mind (John 3:19–20)."},
            {"label": "One man freed", "text": "Not self-freed: the Lord takes his hand as a covenant light, opening blind eyes, exactly as Isaiah promised (Isaiah 42:6–7)."},
            {"label": "They love the dark", "text": "He runs back to tell his brothers, but they mock him; craving human praise, they stay in the dark they love (John 12:37, 43)."},
            {"label": "The blinded mind", "text": "The god of this world veils the gospel; but Paul, chief of sinners, was rescued — and so can you be (2 Corinthians 4:4; 1 Timothy 1:13–16)."},
        ],
        "terms": [
            {"term": "the Allegory of the Cave", "gloss": "Plato’s Republic Bk VII: prisoners mistake shadows for reality. The song reads it as sin and the new birth."},
            {"term": "the Sun", "gloss": "In Plato, the Form of the Good; in the song, the Lord/Christ as the true light (John 8:12; Malachi 4:2)."},
            {"term": "covenant light", "gloss": "Isaiah’s “light to the nations,” given to open blind eyes (Isaiah 42:6–7; Acts 26:18)."},
            {"term": "the god of this world", "gloss": "Satan, who blinds unbelievers so they cannot see the gospel’s glory (2 Corinthians 4:4)."},
            {"term": "“And Can It Be”", "gloss": "Charles Wesley’s hymn; its stanza “Long my imprisoned spirit lay…” closes the song word-for-word."},
        ],
        "discussion": [
            "The freed prisoner doesn’t free himself — the Lord takes his hand. How does that picture of regeneration challenge a “decide for yourself” gospel?",
            "Why do the prisoners prefer the dark? Where does our culture choose comfortable “shadows” over uncomfortable truth?",
            "Paul, chief of sinners, was rescued. How should that fuel a church’s hope for the people it’s tempted to write off?",
        ],
        "contemplation": [
            "Where do you see “the Lord took my hand” in your own coming to faith?",
            "Which “shadows” are you tempted to keep believing because the light feels too strange?",
            "Is there someone you’ve written off whom a rescued “prisoner like me” should be praying for?",
        ],
        "kind": "verse",
        "blocks": [
            [
                "Let's talk about the Cave where the prisoners are bound,",
                "Deep in the dark where no truth can be found.",
                "Chained at the neck and the legs from their youth,",
                "Staring at a wall, kept far from the truth.",
                "Puppets cast shadows by a flickering fire",
                "A world of illusion, all fueled by desire.",
                "It's a counterfeit world of deceptive design,",
                "Where sin is the shadow that's clouding the mind.",
            ],
            [
                "It's the Light vs. the Dark, the cave vs. the Sun,",
                "The battle for vision has already begun.",
                "The cave is the sin where humanity dwells,",
                "The shadows are lies that the world tries to tell.",
                "But the Sun is the Lord, the source of the day,",
                "Calling the prisoners to come out and play.",
                "From lies to the truth, from the night to the dawn,",
                "The chains of the dungeon are finally gone.",
            ],
            [
                "Now one man is freed, unchained from his seat,",
                "By the hand of the Lord he finds his own feet.",
                "Led to the opening, light floods his eyes",
                "Blinded by glory, he lifts to the skies.",
                "He sees real trees, not the shadows they cast;",
                "The darkness is broken, the light's come at last.",
                "Just like Isaiah said it would be:",
                "The prisoners brought from the dark, set free.",
                "The LORD takes your hand as a covenant light,",
                "Opening blind eyes, restoring the sight.",
            ],
            [
                "He runs back to the shadows, full of joy, full of grace,",
                "To tell all his brothers about this new place.",
                "But they laugh and they mock, they say he's insane",
                "They'd rather keep darkness than break from the chain.",
                "The dark feels safe and the light is too strange;",
                "They're scared of the truth, they're scared of the change.",
                "Same as in John, where the signs were all shown,",
                "But their hearts stayed as cold and as hard as a stone.",
                "They craved human praise more than glory above.",
            ],
            [
                "So they stay in the cave, in the dark that they love.",
            ],
            [
                "But if our Gospel is veiled, kept down in the shade,",
                "It's veiled to the perishing, lost and afraid.",
                "The god of this world has blinded their mind,",
                "Keeping unbelievers in the dark, walking blind.",
                "They can't see the light of the Gospel's true grace,",
                "Or the glory of Christ in His radiant face.",
                "For Christ is the Image of God, the true Sun,",
                "Lifting the veil when the victory's won.",
            ],
            [
                "Paul says to Timothy: I know that dark",
                "I lived in the Cave, I was missing the mark.",
                "The chief of sinners, bound up in a chain,",
                "I chased after shadows, I dealt out the pain.",
                "I thought I had vision, I thought I was wise,",
                "But the god of this world had blinded my eyes.",
                "Then God showed me mercy, His grace was so vast",
                "He pulled me from shackles and darkness at last.",
                "A covenant light for the nations to see:",
                "If He rescued a prisoner like me, He'll set you free.",
            ],
            [
                "So don't be the prisoner who clings to the wall,",
                "Believing the shadows and waiting to fall.",
                "The Good that you're chasing has always been Him",
                "The Author of reason, the Light that won't dim.",
                "It's time to walk out of the sin-bound domain,",
                "Trust in the Wisdom that breaks every chain.",
                "Move into the light, let the Son clear the view",
                "The Cave is the old world; He's making things new.",
            ],
            [
                "Long my imprisoned spirit lay",
                "Fast bound in sin and nature's night;",
                "Thine eye diffused a quick'ning ray,",
                "I woke, the dungeon flamed with light;",
                "My chains fell off, my heart was free;",
                "I rose, went forth and followed Thee.",
            ],
        ],
        "refs": [
            "1. John 3:19–20",
            "2. John 8:12; Malachi 4:2",
            "3. Isaiah 61:1; 42:7",
            "4. Isaiah 42:6–7",
            "5. Isaiah 42:6–7",
            "6. John 12:37",
            "7. John 12:43",
            "8. 2 Corinthians 4:3",
            "9. 2 Corinthians 4:4",
            "10. 2 Corinthians 4:4, 6; Colossians 1:15",
            "11. 1 Timothy 1:13",
            "12. 1 Timothy 1:15",
            "13. 1 Timothy 1:13, 16",
            "14. Isaiah 42:6; Acts 26:18",
            "15. John 1:9",
            "16. Acts 12:6–7 (Wesley, “And Can It Be”)",
        ],
    },
    {
        "num": 6,
        "title": "What Christ is Doing in Me",
        "slug": "what-christ-is-doing-in-me",
        "wav": "Hands Wide Open (Chill Mumble Run).wav",
        "about": (
            "A defiant testimony built on 1 Peter: enemies meant it for evil, but "
            "what Christ is doing through me trumps what they're doing to me."
        ),
        "thesis": (
            "Read through Peter’s own failure and restoration, 1 Peter declares "
            "that what Christ is doing through a believer outweighs whatever the "
            "world does to them — so we suffer well, bless our enemies, and "
            "entrust our souls to a faithful Creator."
        ),
        "facts": [
            ("Doctrine", "Suffering · Sanctification · Union with Christ"),
            ("Anchor text", "1 Peter"),
            ("Form", "Chill dancehall (mumble run)"),
            ("Voices", "The Apostle Peter"),
        ],
        "moves": [
            {"label": "The verdict isn’t theirs", "text": "They meant it for evil, but it just dug a well; Heaven turns the whole curse into a verse (Genesis 50:20; 1 Peter 1:6–7)."},
            {"label": "Peter’s own story", "text": "The sword in the garden, the threefold denial by the fire, then restoration on the shore — “feed My sheep” (John 18:10; 21:15–17)."},
            {"label": "Living hope, living stones", "text": "Born again to an imperishable inheritance; once nobody, now a royal priesthood, a holy nation built on the rejected cornerstone (1 Peter 1:3–4; 2:9)."},
            {"label": "Suffer like Christ", "text": "He was reviled but didn’t revile; so arm with the same mind, bless the blow, and entrust your soul to the faithful Creator (1 Peter 2:21–23; 4:19)."},
        ],
        "terms": [
            {"term": "“what Christ is doing through me trumps what they’re doing to me”", "gloss": "The hook — God’s sovereignty over a believer’s suffering (Genesis 50:20; Romans 8:28)."},
            {"term": "living stones / royal priesthood", "gloss": "Peter’s image of the church built on Christ the cornerstone (1 Peter 2:5–9; Psalm 118:22)."},
            {"term": "“He left the stencil”", "gloss": "Echoes the hypogramos of track 1: Christ as the pattern to trace in suffering (1 Peter 2:21)."},
            {"term": "“took an ear off a man in the garden”", "gloss": "Peter cutting off Malchus’s ear — the hothead who later writes “entrust it to the Lord” (John 18:10)."},
        ],
        "discussion": [
            "“What Christ is doing through me trumps what they’re doing to me.” How might that reframe a community facing opposition?",
            "Peter went from drawing a sword to counseling people to entrust themselves to God. How does his failure-and-restoration shape his counsel on suffering?",
            "The song says to “bless the blow.” What does blessing those who wrong us look like together as a church?",
        ],
        "contemplation": [
            "Where do you need the reframe — “what Christ is doing through me trumps what they’re doing to me” — right now?",
            "What would it look like to “bless the blow” with someone who has wronged you?",
            "Can you “entrust the whole soul to the One who made you” today?",
        ],
        "kind": "verse",
        "blocks": [
            [
                "Yeah let 'em talk, let 'em swing",
                "Watch what the King do, watch what the King bring",
            ],
            [
                "They drew up a plan in the dark, thought it landed",
                "I came up grinnin' with my hands wide open-handed",
                "What they meant for the pit just dug me a well",
                "Now I'm drinkin' deep where they wanted me to dwell",
                "They keep score on the hurt, keep tabs on the sting",
                "I keep my eyes on the One pullin' every string",
                "So go 'head, write your verdict, sign it, stamp it, send it",
                "The story ain't yours, and you don't get to end it",
            ],
            [
                "What Christ is doing through me",
                "Trumps what they're doing to me",
                "(Say it again)",
                "What Christ is doing through me",
                "Trumps what they're doing to me",
                "Let 'em do what they do it's already through",
                "'Cause the work in my hands ain't comin' from you",
            ],
            [
                "Used to be the one with the blade in the dark,",
                "Swung at the soldier, left a mark, missed the heart",
                "Took an ear off a man in the garden that night,",
                "Thought the Kingdom was a thing that you seize in a fight.",
                "Then a rooster cut the air and I cracked, I caved,",
                "Warmin' hands at a fire while I left Him to the grave",
                "“Never knew Him,” said it three times to a maid,",
                "Then I wept in the dark for the Man I betrayed.",
                "But He found me on the shore with a fire and some bread,",
                "Asked me “do you love me?” three times for the three I'd said,",
                "“Feed My sheep,” put the staff in the hand held the sword",
                "Now the hothead who slashed writes: entrust it to the Lord.",
            ],
            [
                "New-new, born again, livin' hope in the womb, I",
                "Move through the gloom to a crown they can't loot, I",
                "Got an inheritance kept where the rust can't ruin, the",
                "Trial's just fire on the gold, watch it bloom and",
                "Prove it: the faith come out purer than fortune,",
                "Ransomed not silver or gold paid the portion,",
                "Blood of the Lamb did the buyin', no coupon,",
                "Holy 'cause He's holy, gird the mind, keep it on",
                "Go!",
            ],
            [
                "Quick-quick, watch it, no flinch in the pocket, I'm",
                "Locked in the bracket, they knock and I rock it, I",
                "Talk less, walk slick, they plot and I dodge it, the",
                "Plot's thick, no sweat, I just pocket the profit, I",
                "Flip every fumble to fuel for the furnace, the",
                "Fire don't burn me, it learns me, returns me, I",
            ],
            [
                "Turn the whole curse to a verse and they're nervous, the",
                "Purpose was hidden but Heaven was workin' it",
                "Done, done, watch how the kingdom keep comin', I",
                "Hum through the hate while the haters keep hummin', I",
                "Run through the rumor, the slander, the summons, I",
                "Stand on a rock that they cannot come under",
                "Go!",
            ],
            [
                "What Christ is doing through me",
                "Trumps what they're doing to me",
                "(Louder now)",
                "What Christ is doing through me",
                "Trumps what they're doing to me",
                "Let 'em do what they do it's already through",
                "'Cause the work in my hands ain't comin' from you",
            ],
            [
                "Once we was nobody, now we a nation, a",
                "Royal priesthood, livin'-stone foundation, the",
                "Builder took the rock that they tossed in rotation",
                "Cornerstone now, no more relocation.",
                "But the passions wage war on the soul, so I'm armin',",
                "Keep the conduct so clean that it disarms 'em,",
                "Honor the throne, do good, no alarm, then",
                "Christ left the stencil, every letter, every line,",
                "Trace the Hand that traced it, copy the design:",
                "He was reviled but the Man didn't revile,",
                "Took the strike, kept the style, no denial,",
                "Didn't threaten, just entrusted the trial",
                "To the Judge who is just close the file",
                "By His wounds we was healed, off the road, in the wild,",
                "Strayin' sheep come home to the Shepherd, reconciled.",
            ],
            [
                "She don't preach him a sermon, just live it pure,",
                "Win him without a word, watch the conduct cure;",
                "They curse and we bless, give a blessing for the blow,",
                "Don't repay it with evil, let the good overflow.",
                "Keep the conscience so clean that the slander can't stick,",
                "When they question the hope, give an answer stay quick, but",
                "Gentle, with respect; let 'em swing, take the hit,",
                "'Cause Christ suffered once, the Just for the illegit,",
                "Put to death in the flesh but alive in the Spirit,",
                "Went and made the proclamation every power had to hear it",
                "Now He's up at the right: every angel, every throne,",
                "Authorities subjected the fight's already won.",
            ],
            [
                "Subtract me, they can't",
                "Add to me, they won't",
                "The math was never theirs to run",
                "Every blow's an investment, every loss is a loan",
                "And the interest gets paid by the Son",
            ],
            [
                "So arm up same mind, He suffered, get equipped, I'm",
                "Done with the sin, won't go back to the script, I'm",
                "Loved, and the love throw a cover on a multitude,",
                "Fiery trial ain't strange, don't be shook, dude",
                "Share in the suffering now, share the glory when it's due,",
                "Don't suffer as a crook suffer Christian, see it through,",
                "And entrust the whole soul to the One who made you,",
                "Faithful Creator gonna keep what He gave you",
                "Go!",
            ],
        ],
        "refs": [
            "1. Genesis 50:20",
            "2. John 18:10; Matthew 26:51",
            "3. Matthew 26:69–75; Luke 22:54–62",
            "4. John 21:9–14",
            "5. John 21:15–17",
            "6. 1 Peter 1:3",
            "7. 1 Peter 1:4",
            "8. 1 Peter 1:6–7",
            "9. 1 Peter 1:18–19",
            "10. 1 Peter 1:13, 15–16",
            "11. 1 Peter 2:9",
            "12. 1 Peter 2:6–7; Psalm 118:22",
            "13. 1 Peter 2:11",
            "14. 1 Peter 2:21",
            "15. 1 Peter 2:23",
            "16. 1 Peter 2:24–25; Isaiah 53:5–6",
            "17. 1 Peter 3:1–2",
            "18. 1 Peter 3:9",
            "19. 1 Peter 3:15",
            "20. 1 Peter 3:18",
            "21. 1 Peter 3:19",
            "22. 1 Peter 3:22",
            "23. 1 Peter 4:1",
            "24. 1 Peter 4:8",
            "25. 1 Peter 4:12",
            "26. 1 Peter 4:13",
            "27. 1 Peter 4:15–16",
            "28. 1 Peter 4:19",
        ],
    },
    {
        "num": 7,
        "title": "Acts of the Apostles",
        "slug": "acts-of-the-apostles",
        "wav": "Acts of the Apostles.wav",
        "about": (
            "The dusty, chain-marked, joy-filled road of the apostles — singing "
            "louder than the rage, trading bright gold for a kingdom-come sky."
        ),
        "thesis": (
            "The apostolic mission is a hard, joy-filled road — chains, stones, "
            "and shipwrecks met with songs of praise — because the Lord who "
            "sends His people is the same Lord calling them home."
        ),
        "facts": [
            ("Doctrine", "Mission · Perseverance · Joy in suffering"),
            ("Anchor text", "Acts"),
            ("Form", "Roots reggae anthem"),
            ("Voices", "Paul · Silas"),
        ],
        "moves": [
            {"label": "The road", "text": "Dust on the cloak, chains on the wrists, a fire in the grin — the Word still calls and the road keeps pulling them in (Acts 13:1–3)."},
            {"label": "Singing in prison", "text": "Paul and Silas sing so loud the rage gives in, praising with every last breath even as the prison shakes (Acts 16:25–26)."},
            {"label": "Storm and shipwreck", "text": "Whips, stones, and oars against the gale; they trade bright gold for a “kingdom-come sky” (Acts 27; 2 Corinthians 11:24–25)."},
            {"label": "Calling us home", "text": "All for the cross and the grace they feel, till proud hearts break at His feet (Philippians 2:10; Galatians 6:14)."},
        ],
        "terms": [
            {"term": "the Way", "gloss": "The earliest name for the Christian movement (Acts 24:14; 9:2)."},
            {"term": "“Raise it high”", "gloss": "The praise-refrain — worship as the apostles’ weapon in hardship (Acts 16:25)."},
            {"term": "“trade bright gold for a kingdom-come sky”", "gloss": "Laying up treasure in heaven rather than on earth (Matthew 6:19–20)."},
        ],
        "discussion": [
            "Paul and Silas sing in the jail. How can worship itself be a response to suffering, not just a reward after it?",
            "The apostles “trade bright gold for a kingdom-come sky.” What “gold” does our culture make hardest to hold loosely?",
            "What would a “missionary mindset” — joy in being sent into hard places — look like for this community?",
        ],
        "contemplation": [
            "Could you “sing so loud that the rage gives in” in your current hardship?",
            "What earthly “gold” is hardest for you to hold loosely?",
            "What would it look like to carry “joy liftin my chin” into a hard assignment this week?",
        ],
        "kind": "verse",
        "blocks": [
            [
                "Sand grinds hard on the leather-worn feet",
                "Sun burns deep in my skin",
                "Scrolls half torn",
                "But the Word still calls",
                "And the road keeps pullin' me in",
                "Dust on my cloak",
                "Chains on my wrists",
                "Faith lines cut by the gale",
                "Got a fire in my grin",
                "Joy liftin my chin",
                "And a prison door in my trail",
            ],
            [
                "Raise it high",
                "Glory's on the horizon",
                "Let it shine",
                "Hear the temple crowds cryin'",
                "If you got fear",
                "Better lay it at His throne",
                "'Cause the Lord sends all",
                "And he's calling us home (hey!)",
            ],
            [
                "Old friends swear there's a curse on this Way",
                "Stones keep hailin' down death",
                "But we sing so loud that the rage gives in",
                "And we praise with every last breath",
                "Thunder in Rome and the whips rain down",
                "Oars that bite into gale",
                "We trade bright gold for a kingdom come sky",
                "And the king beams down as we sail",
            ],
            [
                "Raise it high",
                "Glory's on the horizon",
                "Let it shine",
                "Hear the temple crowds cryin'",
                "If you got fear",
                "Better lay it at His throne",
                "'Cause the Lord sends all",
                "And he's calling us home (hey!)",
            ],
            [
                "All for the cross and the grace that we feel",
                "All for the truth that is real",
                "All for the tales that the world calls zeal",
                "Till their proud hearts break at His feet",
            ],
            [
                "Raise it high",
                "Glory's on the horizon",
                "Let it shine",
                "Hear the temple crowds cryin'",
                "If you got fear",
                "Better lay it at His throne",
                "'Cause the Lord sends all",
                "And he's calling us home (hey!)",
            ],
        ],
        "refs": [
            "1. Acts 13:1–3; Romans 1:1",
            "2. Acts 16:23–24; Philippians 1:13",
            "3. Acts 16:25–26",
            "4. 1 Peter 5:7",
            "5. Acts 1:8; Matthew 28:19",
            "6. Acts 24:14; 9:2",
            "7. Acts 14:19; 7:58–60",
            "8. Acts 28:16; 2 Corinthians 11:24–25",
            "9. Acts 27:13–44",
            "10. Matthew 6:19–20",
            "11. Galatians 6:14",
            "12. Philippians 2:10",
        ],
    },
    {
        "num": 8,
        "title": "Freebird's Cage",
        "slug": "freebirds-cage",
        "wav": "Freebird's Cage (Roots Lovers Rock Mix).wav",
        "about": (
            "The lie of the lone rebel: the freedom that's really a cage, the "
            "outlaw badge that was just another kind of chain — until grace."
        ),
        "thesis": (
            "The “free bird” who answers to no one is the most enslaved of all: "
            "self-rule is just another cage. Real freedom isn’t in running — it "
            "comes when grace catches you and mercy wins."
        ),
        "facts": [
            ("Doctrine", "Bondage of the will · Grace · Freedom"),
            ("Anchor text", "John 8 · Romans 6"),
            ("Form", "Lovers rock"),
            ("Voices", "—"),
        ],
        "moves": [
            {"label": "The freebird myth", "text": "“Born wild to run alone,” a restless heart always halfway home; every mile he called “my freedom” just showed him where the trouble’s been."},
            {"label": "The billboard chain", "text": "The outlaw image on the billboard was “just another kind of chain” — the slickest lie he swallowed was that he was free (John 8:32–34; Romans 6:16)."},
            {"label": "A crown of nothing", "text": "A throne built out of smoke, stubbornness preached as gospel, until the “godnamed altar broke” (Ecclesiastes 1:14; 1 Samuel 15:23)."},
            {"label": "Mercy wins", "text": "Freedom isn’t in running; grace came up beside him and Jesus rescued him (John 8:36; Titus 2:11; Ephesians 2:8–9)."},
        ],
        "terms": [
            {"term": "freebird", "gloss": "The cultural ideal of total autonomy; the song argues it’s a cage, not freedom."},
            {"term": "slave to sin", "gloss": "Jesus’ teaching that everyone who sins is a slave, and only the Son sets free (John 8:34–36)."},
            {"term": "“rebellion is as the sin of witchcraft”", "gloss": "An echo of 1 Samuel 15:23, reframing self-rule as bondage rather than liberty."},
            {"term": "“it’s in letting mercy win”", "gloss": "The thesis line: freedom is surrender to grace, not self-assertion."},
        ],
        "discussion": [
            "Our culture sells autonomy as freedom. Where do you see “the lie that I was free” most powerfully marketed?",
            "Jesus says only the Son can set you free. Why can’t we free ourselves from sin’s cage?",
            "The song ends, “freedom ain’t in running, it’s in letting mercy win.” How does that redefine freedom for a group?",
        ],
        "contemplation": [
            "Where have you mistaken self-rule or independence for freedom? How did it become “another kind of chain”?",
            "What “badge” or image have you worn that was “just another kind of chain”?",
            "What would it mean this week to stop running and “let mercy win”?",
        ],
        "kind": "verse",
        "blocks": [
            [
                "I called myself a freebird,",
                "Born wild to run alone",
                "Runaway with a restless heart,",
                "Always halfway home.",
                "Said I didn't need nobody,",
                "Just boots and weathered grin",
                "But every mile I called “my freedom”",
                "Showed me where the trouble's been.",
            ],
            [
                "Yeah, they told me I was free",
                "A lone rebel on the range.",
                "But that picture on the billboard",
                "Was just another kind of chain.",
                "I thought I'd outrun every master,",
                "Thought rules were just for fools not me",
                "But the slickest lie that I swallowed",
                "Was the lie that I was free.",
            ],
            [
                "I wore “outlaw” like a jacket,",
                "Thought it made me look profound.",
                "Sang songs about the open road",
                "Surfin couches out of town.",
                "The highway ain't a hero",
                "It don't save you when you're lost.",
                "Just keeps on taking payment",
                "Gas is only half the cost.",
            ],
            [
                "I swore I'd never bend my knee,",
                "But I bowed to misery…",
            ],
            [
                "Yeah, they told me I was free",
                "A lone rebel on the range.",
                "But that picture on the billboard",
                "Was just another kind of chain.",
                "I thought I'd outrun every master,",
                "Thought rules were just for fools not me",
                "But the slickest lie that I swallowed",
                "Was the lie that I was free.",
            ],
            [
                "I chased a crown of nothing,",
                "Built a throne out of smoke.",
                "Called stubbornness my gospel",
                "Till godnamed altar broke.",
                "Now the man I called “freebird”",
                "Don't look near as tough as him",
                "Turns out freedom ain't in running…",
                "It's in letting mercy win.",
            ],
            [
                "Every time I said, “I'm doing fine,”",
                "I was practicing a line…",
            ],
            [
                "Yeah, they told me I was free",
                "A lone rebel on the range.",
                "But that badge I wore so proudly",
                "Was just another kind of chain.",
                "I thought I'd outrun every master,",
                "But I had chains I couldn't see",
                "Then grace came up beside me",
                "And Jesus rescued me",
            ],
        ],
        "refs": [
            "1. Romans 6:16; Matthew 6:24",
            "2. John 8:32–34",
            "3. Romans 6:16",
            "4. Ecclesiastes 1:14",
            "5. 1 Samuel 15:23",
            "6. John 8:36; Galatians 5:1",
            "7. John 8:34; 2 Peter 2:19",
            "8. Titus 2:11; Ephesians 2:8–9",
        ],
    },
    {
        "num": 9,
        "title": "Worship is the Warfare",
        "slug": "worship-is-the-warfare",
        "wav": "The Lyre and the Spear (Techno Reggae Version).wav",
        "about": (
            "David's harp against Saul's tormenting spirit — a shadow of the "
            "Better David, whose song is the sword that crushes the serpent."
        ),
        "thesis": (
            "When David’s harp drove back the spirit tormenting Saul, it pictured "
            "the gospel: worship is warfare. The Better David didn’t dodge the "
            "spear — He took it, disarmed the powers, and crushed the serpent’s "
            "head."
        ),
        "facts": [
            ("Doctrine", "Spiritual warfare · Typology · Christus Victor"),
            ("Anchor text", "1 Samuel 16 · Colossians 2:15"),
            ("Form", "Techno reggae"),
            ("Voices", "David · Martin Luther"),
        ],
        "moves": [
            {"label": "A man who plays well", "text": "Saul is tormented by a spirit; servants seek a son of Jesse to raise a melody — “a weapon to wield” (1 Samuel 16:14–17)."},
            {"label": "The skillful hand", "text": "David: a man of valor, prudent in speech, prepared in obscurity for the court — and the Lord is with him (1 Samuel 16:18, 23)."},
            {"label": "The Better David", "text": "Saul threw the spear and David moved aside; but Christ didn’t flee — He let the spear nail Him to break every chain (John 19:34; 1 Samuel 18:10–11)."},
            {"label": "The serpent crushed", "text": "He disarmed the rulers, put them to open shame, and crushed the serpent’s head; “one little word shall fell him” (Colossians 2:15; Genesis 3:15)."},
        ],
        "terms": [
            {"term": "“worship is the warfare, the song is the sword”", "gloss": "The hook — praise as the believer’s weapon against the darkness."},
            {"term": "the Better David", "gloss": "Christ as the true anointed king that David only foreshadowed."},
            {"term": "“one little word shall fell him”", "gloss": "A line from Luther’s hymn “A Mighty Fortress Is Our God.”"},
            {"term": "disarmed the rulers", "gloss": "Christ’s triumph over the spiritual powers at the cross (Colossians 2:15)."},
        ],
        "discussion": [
            "The song calls worship a weapon, not just a feeling. How might corporate praise function as spiritual warfare in a dark season?",
            "David dodged Saul’s spear, but Christ took the spear. Why does the song make that contrast the heart of the gospel?",
            "What does it mean for a church to “strike up the anthem of terrible joy” when it’s under attack?",
        ],
        "contemplation": [
            "Where do you need to “strike up the anthem of terrible joy” against discouragement this week?",
            "Is your worship a refuge from the battle, or a weapon in it?",
            "The Better David “didn’t dodge the weapon.” Where is He asking you to trust Him in the pain rather than flee it?",
        ],
        "kind": "verse",
        "blocks": [
            [
                "Shadows falling heavy on the palace floor",
                "The old king is fading, he can't rule anymore",
                "Tormented by a spirit, looking for relief",
                "Caught in the trap of his own unbelief",
                "Servants call out, “Find a man who plays well”",
                "To drive back the darkness and break this spell",
                "We need a son of Jesse, summoned from the field",
                "To raise up a melody, a weapon to wield",
            ],
            [
                "He's a man of valor, a man of war",
                "Prudent in speech, knowing what he's fighting for",
                "Prepared in obscurity, ready for the light",
                "To stand before kings and push back the night",
            ],
            [
                "Worship is the warfare, the song is the sword",
                "We fight the battle with the notes of the Lord",
                "When the heavy spirit comes to steal and destroy",
                "We strike up the anthem of terrible joy",
                "With a skillful hand, let the music begin",
                "'Cause the Lord is with him, yeah, the Lord is with him!",
            ],
            [
                "It's not just the song, it's the heart of the man",
                "A vessel of honor in the Master's plan",
                "Self-controlled, disciplined, set apart",
                "Abiding in the Vine with a purified heart",
                "From the sheepfold to the court, see the young man rise",
                "With the power of the Spirit burning in his eyes",
                "Driving out the gloom with a prayer and a chord",
                "A picture of the coming, conquering Lord",
            ],
            [
                "Worship is the warfare, the song is the sword",
                "We fight the battle with the notes of the Lord",
                "When the heavy spirit comes to steal and destroy",
                "We strike up the anthem of terrible joy",
                "With a skillful hand, let the music begin",
                "'Cause the Lord is with him, yeah, the Lord is with him!",
            ],
            [
                "But David was a picture, a shadow of the King",
                "Who came to finish what the prophets sing",
                "Saul threw the spear, and David moved aside",
                "But the Better David came to open His arms wide",
                "He didn't dodge the weapon, He didn't flee the pain",
                "He let the spear nail Him to break every chain",
                "He disarmed the rulers, put them to open shame",
                "And crushed the serpent's head in His holy Name!",
            ],
            [
                "Worship is the warfare, the song is the sword",
                "We fight the battle with the notes of the Lord",
                "When the heavy spirit comes to steal and destroy",
                "We strike up the anthem of terrible joy",
                "The Prince of Darkness grim, we tremble not for him",
                "'Cause the Lord is with us, yeah, the Lord is with us!",
            ],
            [
                "One little word shall fell him",
                "The King of Kings is upon the throne",
                "The Better David has come home",
                "The Lord is with Him.",
            ],
        ],
        "refs": [
            "1. 1 Samuel 16:14",
            "2. 1 Samuel 16:16–17",
            "3. 1 Samuel 16:18–19",
            "4. 1 Samuel 16:18",
            "5. 1 Samuel 16:23; John 10:10",
            "6. 1 Samuel 16:18",
            "7. 1 Samuel 16:11–12",
            "8. 1 Samuel 16:13",
            "9. 1 Samuel 18:10–11; 19:9–10",
            "10. John 19:34; Isaiah 53:7",
            "11. Colossians 2:15",
            "12. Genesis 3:15; Romans 16:20",
            "13. Colossians 2:15 (Luther, “A Mighty Fortress”)",
            "14. Revelation 19:16; 1 Timothy 6:15",
        ],
    },
    {
        "num": 10,
        "title": "Solid Ground",
        "slug": "solid-ground",
        "wav": "Solid Ground.wav",
        "about": (
            "Not a disembodied heaven of harps and clouds — a bodily "
            "resurrection and a new creation as solid as the dirt beneath your "
            "feet."
        ),
        "thesis": (
            "Heaven isn’t a disembodied fog of harps and clouds. Scripture "
            "promises a bodily resurrection and a new creation as solid as the "
            "dirt under your feet — and the risen body of Christ is the pattern "
            "and the proof."
        ),
        "facts": [
            ("Doctrine", "Resurrection · New creation · Eschatology"),
            ("Anchor text", "1 Corinthians 15 · Luke 24"),
            ("Form", "Roots reggae"),
            ("Voices", "—"),
        ],
        "moves": [
            {"label": "They sold you a fog", "text": "The lie of a soul drifting in mist where harps are strummed. “That’s not it. Heaven is the new and perfect here” (Revelation 21:1–3)."},
            {"label": "Solid as the dirt", "text": "The world to come is heavier, not lighter — matter, not steam; you’ll even have taste buds in heaven (Isaiah 25:6; 2 Peter 3:13)."},
            {"label": "Study at the tomb", "text": "The risen body had scars, bones, and feet, ate fish, yet passed through bolted doors — the same flesh, raised and glorified (Luke 24:39–43; John 20:27)."},
            {"label": "Matter isn’t garbage", "text": "He made the body, will raise it, and walked one out of the grave; the future is “not the end of flesh” but part of what He came to save (1 Corinthians 15:20–23; Romans 8:11)."},
        ],
        "terms": [
            {"term": "disembodied bliss", "gloss": "The popular (Platonic/Gnostic) picture of heaven the song rejects."},
            {"term": "first fruits / firstborn from the ground", "gloss": "Christ’s resurrection guarantees and patterns ours (1 Corinthians 15:20–23; Colossians 1:18)."},
            {"term": "solid ground", "gloss": "The song’s image for the physical reality of the new creation (Revelation 21; Hebrews 11:16)."},
            {"term": "“Salty. Sour. Bitter. Sweet.”", "gloss": "The embodied, sensory reality of the world to come (Isaiah 25:6)."},
        ],
        "discussion": [
            "How is the Bible’s picture of resurrection different from the “harps and clouds” version most people imagine — and why does the difference matter?",
            "“Study at the tomb” — Christ’s risen body is the pattern for ours. Why does His physical resurrection matter so much for our hope?",
            "If the body isn’t “luggage you abandon,” how should that shape how a church views work, creation, and the physical world?",
        ],
        "contemplation": [
            "Have you secretly pictured heaven as “disembodied bliss”? How does a solid, embodied hope change you?",
            "How does “you’ll have taste buds in heaven” change the way you treat your body now?",
            "Put your hand against the wall — feel the weight. What “rumor of the country where the King already came” do you need to trust today?",
        ],
        "kind": "verse",
        "blocks": [
            [
                "They sold you on a fog: a disembodied hum,",
                "A soul without a body in a mist where harps are strummed,",
                "Floating somewhere off the edge of a pale and distant sphere",
                "Forget it. That's not it. Heaven is the new and perfect here.",
            ],
            [
                "Scripture promises the opposite of clouds and endless air:",
                "Not a ghost up in the rafters, not a wisp without a where.",
                "A new creation's coming and it's gonna be our home",
                "As solid as this world is now built for spirit flesh and bone.",
                "You were told the end was vapor, you were told the end was",
                "mist,",
                "Handed harps and floating halos and a disembodied bliss",
                "But the dirt beneath your sneakers is more honest than that",
                "dream:",
                "The world to come is heavier. It's matter. It's not steam.",
            ],
            [
                "Solid ground, solid ground",
                "Not a cloud, not a harp, not a soul just drifting 'round;",
                "The world to come is solid as the dirt beneath your feet",
                "You'll have taste buds up in heaven. Salty. Sour. Bitter.",
                "Sweet.",
            ],
            [
                "You want to know the substance? Go and study at the tomb",
                "The body that walked out of it's the pattern and the proof.",
                "They could lay their hands upon him: feel the scars, the breath,",
                "the heat;",
                "He ate the fish in front of them. He had bones. He had feet.",
                "And yet he passed through bolted doors exceptional, made",
                "new:",
                "The same flesh, raised and glorified, and that flesh is coming",
                "through.",
                "He's the first fruits of the harvest, he's the firstborn from the",
                "ground",
                "So the manner of his rising is the manner you'll be found.",
            ],
            [
                "Solid ground, solid ground",
                "Not a cloud, not a harp, not a soul just drifting 'round;",
                "The world to come is solid as the dirt beneath your feet",
                "You'll have taste buds up in heaven. Salty. Sour. Bitter. Sweet.",
            ],
            [
                "So matter isn't garbage that you shed when you expire,",
                "And the body isn't luggage you abandon to the fire.",
                "He made it, and he'll raise it, and he walked one from the",
                "grave",
                "The future's not the end of flesh. It's part of what he came to",
                "save.",
                "You want to read the world to come? Then study how he",
                "stood:",
                "Not less real this world more. And solid. And for good.",
            ],
            [
                "Put your hand against the wall. Feel the cold, the weight, the",
                "grain.",
                "That's a rumor of the country where the King already came.",
                "It's not vapor. It's not theory. It's not somewhere you ascend",
                "It's a ground that holds your weight. And it's waiting. At the",
                "end.",
            ],
        ],
        "refs": [
            "1. Revelation 21:1–3",
            "2. 2 Peter 3:13; Isaiah 65:17",
            "3. Isaiah 25:6; Luke 22:30",
            "4. Luke 24:39",
            "5. John 20:27",
            "6. Luke 24:41–43",
            "7. John 20:19, 26",
            "8. 1 Corinthians 15:20, 23; Colossians 1:18",
            "9. 1 John 3:2; 1 Corinthians 15:49",
            "10. 1 Corinthians 6:13–14, 19",
            "11. Romans 8:11",
            "12. Romans 8:23",
            "13. Hebrews 11:16; Luke 24:39",
        ],
    },
    {
        "num": 11,
        "title": "Matthew 28",
        "slug": "matthew-28",
        "wav": "The Resurrection of Jesus_ Matt 28.wav",
        "about": (
            "A spoken walk through the final chapter of Matthew — two great "
            "denials that the tomb is empty, then the positive: Jesus is Lord, "
            "worshipped by the whole world."
        ),
        "attribution": {
            "text": (
                "This track sets to music an exposition of Matthew 28 by Dick "
                "Lucas — longtime rector of St Helen’s Bishopsgate, London, and "
                "a formative voice in expository preaching."
            ),
            "links": [
                ("About Dick Lucas", "https://www.st-helens.org.uk/resources/dick-lucas/"),
                ("Listen to the original talk", "https://www.st-helens.org.uk/resources/talk/59088/"),
            ],
        },
        "thesis": (
            "Matthew 28 first establishes the negative — twice over, “He is not "
            "here” — before the glorious positive: the One who was in the tomb "
            "is now the worshipped Lord of glory, sending His people to the "
            "whole world."
        ),
        "facts": [
            ("Doctrine", "Resurrection · Lordship · Mission"),
            ("Anchor text", "Matthew 28"),
            ("Form", "Spoken word · teaching"),
            ("Voices", "Dick Lucas"),
        ],
        "moves": [
            {"label": "The empty tomb", "text": "An undramatic visit, then the earthquake and the angel: “He is not here, he has risen, just as he said” (Matthew 28:1–7)."},
            {"label": "The two denials", "text": "The angel’s word and the guards’ bribed cover-story both testify to the same negative fact — the body is gone (Matthew 28:11–15)."},
            {"label": "The positive", "text": "On the mountain the disciples worship Him — though some doubted — and He declares, “All authority in heaven and on earth has been given to me” (Matthew 28:16–18)."},
            {"label": "The whole world", "text": "Lord of all, He sends His people to disciple all nations, present with them to the very end of the age (Matthew 28:19–20)."},
        ],
        "terms": [
            {"term": "the two denials", "gloss": "The two paragraphs (the angel, then the guards) that establish the negative fact: Jesus is no longer in the tomb."},
            {"term": "the Great Commission", "gloss": "Christ’s command to make disciples of all nations, baptizing and teaching them (Matthew 28:19–20)."},
            {"term": "“a missionary gospel”", "gloss": "The teaching’s conclusion: Matthew ends not with an ending but the beginning of a worldwide story that never ends."},
        ],
        "discussion": [
            "Why does the chapter spend so long on the negative — “He is not here” — before the positive?",
            "The disciples worship even as “some doubted.” What’s encouraging about that honest detail for a church?",
            "“All authority… therefore go.” How does Christ’s lordship fuel the mission to the whole world together?",
        ],
        "contemplation": [
            "The empty tomb is “extraordinarily undramatic.” Where do you miss God because you’re looking for drama?",
            "Do you worship Christ as Lord even while some doubt still lingers?",
            "If “all authority” belongs to Him, what “go” is He giving you?",
        ],
        "kind": "prose",
        "blocks": [
            "Matthew 28 The whole chapter has a grand unity and simplicity. First of all it's strong on the negative before the wonderfully positive Great Commission. So let's go through it briefly. Verse one. After the Sabbath at dawn on the first day of the week, Mary Magdalene and the other Mary went to look at the tomb. Well, that's extraordinarily undramatic.",
            "All that is said is that they went to look at the tomb and it doesn't seem they had any other purpose or expected anything else.",
            "Then the first denial and then the second denial, I'll read them both. The first denial. There was a violent earthquake for an angel of the Lord came down from heaven and going to the tomb, rolled back the stone and sat on it. His appearance was like lightning, his clothes were white as snow. The guards were so afraid of him that they shook and became like dead men. The angel said to the women, don't be afraid, for I know you're looking for Jesus who was crucified. He is not here.",
            "Here is the first denial. He is not here, he has risen just as he said. Come, see the place where he lay. Then go quickly and tell his disciples he has risen from the dead and gone ahead of you into Galilee. There you will see him. Now I have told you. So the women hurried away from the tomb, afraid yet filled with joy and ran to tell his disciples.",
            "Suddenly Jesus met them and said, “Greetings.” They came to him, clasped his feet and worshipped him. Then Jesus said to them, do not be afraid, go and tell my brothers to go to Galilee where they will see me. So they find him alive, they acknowledge him as Lord and they're to go to his brothers and say he is alive. That's the first great denial, summed up in a few words in verse six. He is not here. That is the purpose of the paragraph. That is the angelic message. Don't look here because he is not here.",
            "Then the second denial is in verses 11 to 15. While the women were on their way, some of the guards went into the city and reported to the chief priests everything that had happened. When the chief priests had met with the elders and devised a plan, they gave the soldiers a large sum of money, telling them you are to say his disciples came during the night and stole him away while we were asleep. If this report gets to the governor, we will satisfy him and keep you out of trouble. So the soldiers took the money, no doubt gladly, and did as they were instructed. And this story has been widely circulated among the Jews to this very day.",
            "So that's the second denial. Here are two great denials. He is not here, the body has gone. These two paragraphs are there to say quite simply the negative fact that Jesus is no longer in the tomb.",
            "Then comes the positive. The negative having been firmly established, now comes the positive read. Then the 11 disciples went to Galilee to the mountain where Jesus had told them to go. And when they saw him, they worshipped him. Now you see he is Lord of glory, no longer a dead man.",
            "But some doubted, a delightful little touch, so realistic. Then Jesus came to them and said, all authority in heaven and on earth has been given to me.",
            "Therefore go and make disciples of all nations, baptizing them in the name of the Father and the Son and the Holy Spirit, teaching them to observe everything I've commanded you. And surely I am with you always to the very end of the age. So what does that tell us? Quite simply, first, all authority in heaven and earth belongs to the Lord Jesus Christ. It's impossible to state his position as Lord more clearly than that. There's no other authority. Jesus is Lord.",
            "He is not one among others, he is the Lord God himself. Secondly, all nations must now bow before him. That is the whole world. He's not come now for a nation, but for a world. He is Lord therefore and Lord of all. And this Lord will be with his people to the end of time.",
            "It's really meant to be, I think, a very simple chapter saying the one who was in the tomb is now recognized to be the Lord of glory and naturally he's worshipped as God. At the start of chapter 28, a body in a tomb. At the end, the Lord of glory worshipped by his people. At the start it seemed to be the end of the story. At the conclusion in Matthew 28, it's the beginning of a story that never ends.",
            "Matthew therefore by definition is a missionary gospel. The Lord who is to be worshipped by the whole world.",
            "The whole world. The whole world. The whole world.",
        ],
        "refs": [
            "1. Matthew 28:1",
            "2. Matthew 28:2–3",
            "3. Matthew 28:4",
            "4. Matthew 28:5–6",
            "5. Matthew 28:7",
            "6. Matthew 28:8",
            "7. Matthew 28:9",
            "8. Matthew 28:10",
            "9. Matthew 28:11",
            "10. Matthew 28:12–13",
            "11. Matthew 28:15",
            "12. Matthew 28:16",
            "13. Matthew 28:17",
            "14. Matthew 28:18",
            "15. Matthew 28:19",
            "16. Matthew 28:20",
        ],
    },
    {
        "num": 12,
        "title": "Nations Gonna Come",
        "slug": "nations-gonna-come",
        "wav": "Psalm 117.wav",
        "about": (
            "A postmillennial doxology — every tribe and tongue praising the "
            "Lord, the earth filled with His glory as the waters cover the sea."
        ),
        "thesis": (
            "A doxology of hope: the gospel will fill the whole earth as the "
            "waters cover the sea, every tribe and tongue will praise the Lord, "
            "and what the cross has won will be fully done."
        ),
        "facts": [
            ("Doctrine", "Missions · Kingdom · Eschatology of hope"),
            ("Anchor text", "Psalm 117 · Psalm 72"),
            ("Form", "Reggae hymn"),
            ("Voices", "Isaac Watts"),
        ],
        "moves": [
            {"label": "All ye nations", "text": "Psalm 117’s call: every tongue praising, His mercy reigning through every land, His truth standing forever (Psalm 117:1–2; Revelation 7:9)."},
            {"label": "He will fill the world", "text": "Binding up wounds, setting captives free; the earth restored and justice spreading “as the waters run” (Habakkuk 2:14; Isaiah 61:1)."},
            {"label": "Gospel light over idols", "text": "Ancient shadows flee, the idols fall and the lies grow mute, the meek inherit the earth, and Christ alone is King (Isaiah 2:18; Matthew 5:5)."},
            {"label": "Jesus shall reign", "text": "Watts’s hymn woven in: His rule from shore to shore till moons wax no more, every knee bowing (Psalm 72:8–11; Philippians 2:10–11)."},
        ],
        "terms": [
            {"term": "“Let Thy Kingdom come”", "gloss": "The petition of the Lord’s Prayer, used as the song’s refrain (Matthew 6:10)."},
            {"term": "“fill the earth as the waters cover the sea”", "gloss": "The promised global scope of God’s glory (Numbers 14:21; Habakkuk 2:14)."},
            {"term": "“Jesus Shall Reign”", "gloss": "Isaac Watts’s hymn, a paraphrase of Psalm 72, quoted in the closing verses."},
            {"term": "“the meek inherit the earth”", "gloss": "The kingdom reversal Christ promised (Matthew 5:5; Psalm 37:11)."},
        ],
        "discussion": [
            "The song is relentlessly hopeful about the gospel’s reach. How does that hope change the way a church prays “Thy kingdom come”?",
            "“Every tribe and tongue” will praise. How should that future shape your community’s view of missions now?",
            "What “idols” and “ancient shadows” in our culture do you most long to see fall?",
        ],
        "contemplation": [
            "Does your imagination actually expect the gospel to fill the earth “as the waters cover the sea”?",
            "How does the certainty of “every tribe and tongue” praising shape your prayers this week?",
            "What would it mean to “let Thy Kingdom come” in your own heart first?",
        ],
        "kind": "verse",
        "blocks": [
            [
                "O all ye nations, praise the Lord,",
                "Each with a diff'rent tongue;",
                "In every language learn His word,",
                "And let His name be sung.",
                "His mercy reigns through every land;",
                "Proclaim His grace abroad;",
                "For ever firm His truth shall stand",
                "Praise ye the faithful God.",
            ],
            [
                "He will fill the world",
                "With His majesty,",
                "Binding up the wounds,",
                "Setting captives free;",
                "Every tribe and tongue",
                "Shall His glory see",
                "All the earth restored",
                "In His victory.",
                "Justice shall spread",
                "As the waters run,",
                "Darkness chased away",
                "By the rising Sun;",
                "What the cross has won",
                "Shall be fully done,",
                "Oh Lord,",
                "Let Thy Kingdom come!",
            ],
            [
                "His gospel light shall chase the dark",
                "Where ancient shadows lie;",
                "The idols fall, the lies grow mute,",
                "As truth is lifted high.",
                "By Word and Spirit hearts are won,",
                "New songs through nations ring;",
                "The meek inherit all the earth,",
                "And Christ alone is King.",
            ],
            [
                "He will fill the world",
                "With His majesty,",
                "Binding up the wounds,",
                "Setting captives free;",
                "Every tribe and tongue",
                "Shall His glory see",
                "All the earth restored",
                "In His victory.",
                "Justice shall spread",
                "As the waters run,",
                "Darkness chased away",
                "By the rising Sun;",
                "What the cross has won",
                "Shall be fully done,",
                "Oh Lord,",
                "Let Thy Kingdom come!",
            ],
            [
                "Jesus shall reign where'er the sun,",
                "His daily course doth run;",
                "From shore to shore His rule extends,",
                "Till moons shall wax no more.",
                "He comes the pris'ners to release,",
                "The wounded He shall heal;",
                "All kings shall bow, all tongues shall confess",
                "The pow'r His truth shall seal.",
            ],
            [
                "He will fill the world",
                "With His majesty,",
                "Binding up the wounds,",
                "Setting captives free;",
                "Every tribe and tongue",
                "Shall His glory see",
                "All the earth restored",
                "In His victory.",
                "Justice shall spread",
                "As the waters run,",
                "Darkness chased away",
                "By the rising Sun;",
                "What the cross has won",
                "Shall be fully done,",
                "Oh Lord,",
                "Let Thy Kingdom come!",
            ],
        ],
        "refs": [
            "1. Psalm 117:1; Revelation 7:9",
            "2. Acts 2:11; Revelation 5:9",
            "3. Psalm 117:2",
            "4. Numbers 14:21; Habakkuk 2:14",
            "5. Psalm 147:3; Isaiah 61:1",
            "6. Isaiah 61:1; Luke 4:18",
            "7. Revelation 7:9",
            "8. Amos 5:24; Isaiah 11:9",
            "9. Malachi 4:2; Luke 1:78–79",
            "10. Matthew 6:10",
            "11. Isaiah 9:2",
            "12. Isaiah 2:18",
            "13. Zechariah 4:6",
            "14. Matthew 5:5; Psalm 37:11",
            "15. Psalm 72:8 (Watts, “Jesus Shall Reign”)",
            "16. Zechariah 9:10",
            "17. Psalm 72:12–13",
            "18. Psalm 72:11; Philippians 2:10–11",
        ],
    },
]
